{
  "post_stream": {
    "posts": [
      {
        "id": 5823,
        "name": "Vivek Singh",
        "username": "viveksinghggits",
        "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png",
        "created_at": "2019-12-14T07:23:08.304Z",
        "cooked": "<p>I have successfully managed foundationDB to run on kubernetes with <code>redundancy_mode</code> <code>single</code> and all the pods (<code>4</code> pods) are running fine. Now the first problem is the name of the pods are in below format, as you can say we dont actually get to know which component of foundationDB that pod is</p>\n<pre><code class=\"lang-auto\">foundationdbcluster-sample-1                   2/2     Running   0          15h\nfoundationdbcluster-sample-2                   2/2     Running   0          15h\nfoundationdbcluster-sample-3                   2/2     Running   0          15h\nfoundationdbcluster-sample-4                   2/2     Running   0          15h\n\n</code></pre>\n<p>another issue that I facing is when I <code>EXEC</code> into a pod and try to access the <code>fdbcli</code> I get below error</p>\n<pre><code class=\"lang-auto\">root@foundationdbcluster-sample-1:/var/dynamic-conf# fdbcli\nUsing cluster file `/var/dynamic-conf/fdb.cluster'.\n\nThe database is unavailable; type `status' for more information.\n\nWelcome to the fdbcli. For help, type `help'.\nfdb&gt; \n\n</code></pre>\n<p>Here we can see that the <code>database is unavailable</code>, and thats why when we try to run another command in <code>fdbcli</code> we get below error</p>\n<pre><code class=\"lang-auto\">fdb&gt; writemode on\nfdb&gt; set name vivek\n\nWARNING: Long delay (Ctrl-C to interrupt)\n\nThe database is unavailable; type `status' for more information.\n\n</code></pre>\n<p>Now if i go ahead and try to configure the new database using the command <code>configure new ssd single</code> below is the output that I get</p>\n<pre><code class=\"lang-auto\">fdb&gt; configure new ssd single\n\nWARNING: Long delay (Ctrl-C to interrupt)\n\nThe database is unavailable; type `status' for more information.\n\n</code></pre>\n<p>My question is how to go about setting up new database. Below is the content of the <code>/var/dynamic-conf/fdb.cluster</code></p>\n<pre><code class=\"lang-auto\">root@foundationdbcluster-sample-1:/var/dynamic-conf# more fdb.cluster \nfoundationdbcluster_sample:56TI2smTyVsGd5Xav0yu99ZAMPTA7z7s@10.244.0.16:4500:tls\nroot@foundationdbcluster-sample-1:/var/dynamic-conf#      \nroot@foundationdbcluster-sample-1:/var/dynamic-conf# \nroot@foundationdbcluster-sample-1:/var/dynamic-conf# more fdbmonitor.conf \n[general]\nkill_on_configuration_change = false\nrestart_delay = 60\n[fdbserver.1]\ncommand = /var/dynamic-conf/bin/6.2.11/fdbserver\ncluster_file = /var/fdb/data/fdb.cluster\nseed_cluster_file = /var/dynamic-conf/fdb.cluster\npublic_address = 10.244.0.20:4500:tls\nclass = storage\ndatadir = /var/fdb/data\nlogdir = /var/log/fdb-trace-logs\nloggroup = foundationdbcluster-sample\nlocality_instance_id = 1\nlocality_machineid = foundationdbcluster-sample-1\nlocality_zoneid = foundationdbcluster-sample-1\nknob_disable_posix_kernel_aio=1\nroot@foundationdbcluster-sample-1:/var/dynamic-conf# \n\n</code></pre>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-14T07:23:08.304Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 957,
        "reads": 73,
        "readers_count": 72,
        "score": 4794.6,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "Vivek Singh",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 700,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 5824,
        "name": "Vivek Singh",
        "username": "viveksinghggits",
        "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png",
        "created_at": "2019-12-16T07:07:11.730Z",
        "cooked": "<p>This seems to work if I create the cluster using <code>double</code> <code>redundancy_mode</code>. I am creating the local cluster using <a href=\"https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/config/samples/local_cluster.yaml\" rel=\"nofollow noopener\">this</a> file.</p>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-16T07:07:11.730Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 62,
        "readers_count": 61,
        "score": 17.4,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "Vivek Singh",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/config/samples/local_cluster.yaml",
            "internal": false,
            "reflection": false,
            "title": "fdb-kubernetes-operator/local_cluster.yaml at master \u00b7 FoundationDB/fdb-kubernetes-operator \u00b7 GitHub",
            "clicks": 24
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 700,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 5836,
        "name": "John Brownlee",
        "username": "john_brownlee",
        "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png",
        "created_at": "2019-12-16T15:31:06.761Z",
        "cooked": "<blockquote>\n<p>Now the first problem is the name of the pods are in below format, as you can say we dont actually get to know which component of foundationDB that pod is</p>\n</blockquote>\n<p>All of the pods are running fdbserver processes. I\u2019ve been thinking about some changes to the name format to clarify what role they\u2019re serving and make the instance IDs more consistent. I\u2019ll file an issue on that today.</p>\n<blockquote>\n<p>another issue that I facing is when I  <code>EXEC</code>  into a pod and try to access the  <code>fdbcli</code>  I get below error</p>\n</blockquote>\n<p>The operator should create the initial database configuration for you. If you want to change it, you can run <code>configure ssd single</code>, but it\u2019s better to do that by editing the spec in Kubernetes and letting the operator roll out the new configuration.</p>\n<p>Can you run <code>kubectl describe foundationdbcluster foundationdbcluster-sample</code> and see if the describe output indicates that the cluster has been created successfully? The status will indicate whether the cluster has been successfully reconciled, and will have events for the major stages of reconciliation, including each attempt to configure the database. It\u2019s possible that the configuration command is failing.</p>\n<p>There will also be trace logs in <code>/var/log/fdb-trace-logs</code>. Those logs may provide more information about connection errors, TLS errors, or something else that\u2019s preventing the configuration from working.</p>\n<p>What kind of Kubernetes environment are you using for these tests?</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-16T15:31:06.761Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 7,
        "reads": 60,
        "readers_count": 59,
        "score": 52.0,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "John Brownlee",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 3,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 5838,
        "name": "Vivek Singh",
        "username": "viveksinghggits",
        "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png",
        "created_at": "2019-12-16T15:44:46.559Z",
        "cooked": "<p>Hi <a class=\"mention\" href=\"/u/john_brownlee\">@john_brownlee</a><br>\nI am not pretty sure about the CR status when I created the cluster using <code>redundancy_mode</code> as <code>single</code> but now I have changed that to be double and things seem to be working as of now. There are chances that I will have to run this in single redundancy_mode again, and I will update that here if I face any issues.<br>\nI am testing these things on a cluster that is provisioned through <a href=\"https://kind.sigs.k8s.io/\" rel=\"nofollow noopener\">Kind</a>.</p>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-16T15:45:43.972Z",
        "reply_count": 1,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 55,
        "readers_count": 54,
        "score": 21.0,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "Vivek Singh",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://kind.sigs.k8s.io/",
            "internal": false,
            "reflection": false,
            "title": "kind",
            "clicks": 3
          }
        ],
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 3,
          "username": "john_brownlee",
          "name": "John Brownlee",
          "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 700,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 5839,
        "name": "John Brownlee",
        "username": "john_brownlee",
        "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png",
        "created_at": "2019-12-16T16:33:13.698Z",
        "cooked": "<p>OK. I\u2019ll try reproducing this problem in my local environment. I haven\u2019t done much testing with a single replication config, since it\u2019s not a configuration we use here, but if you have a use case for it we should be able to support it. The only hard blocker with that I\u2019m aware of is that any change that requires recreating pods would take the database unavailable, because we would lose the only coordinator. We could address that by using more coordinators in single replication mode, or by adding an option to handle those kind of updates by replacing the old pods rather than deleting and recreating them.</p>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-16T16:33:13.698Z",
        "reply_count": 2,
        "reply_to_post_number": 4,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 50,
        "readers_count": 49,
        "score": 20.0,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "John Brownlee",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 700,
          "username": "viveksinghggits",
          "name": "Vivek Singh",
          "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 3,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 5840,
        "name": "Vivek Singh",
        "username": "viveksinghggits",
        "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png",
        "created_at": "2019-12-16T16:37:23.938Z",
        "cooked": "<p>Hi <a class=\"mention\" href=\"/u/john_brownlee\">@john_brownlee</a><br>\nyeah the problem of losing the coordinator makes sense to me now. But as of now I am going ahead with the <code>double redundancy</code> mode and will update here if I have to get the things working with <code>single redundancy mode</code>.</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-16T16:37:23.938Z",
        "reply_count": 0,
        "reply_to_post_number": 5,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 47,
        "readers_count": 46,
        "score": 14.4,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "Vivek Singh",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 3,
          "username": "john_brownlee",
          "name": "John Brownlee",
          "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 700,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 5847,
        "name": "Vivek Singh",
        "username": "viveksinghggits",
        "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png",
        "created_at": "2019-12-17T07:35:43.459Z",
        "cooked": "<p>Hi <a class=\"mention\" href=\"/u/john_brownlee\">@john_brownlee</a><br>\nSo, I observed a pattern here, even if we run the cluster in double redundancy mode the pods get the running state but when we <code>exec</code> into the pod to access the <code>fdbcli</code> we get below errors for some time.<br>\nEither</p>\n<pre><code class=\"lang-auto\">Unexpected error loading cluster file `/var/dynamic-conf/fdb.cluster': 1513 File could not be read\n</code></pre>\n<p>or</p>\n<pre><code class=\"lang-auto\">\nUsing cluster file `/var/dynamic-conf/fdb.cluster'.\n\nThe database is unavailable; type `status' for more information.\n\nWelcome to the fdbcli. For help, type `help'.\n</code></pre>\n<p>and after some time we get <code>database is available</code> message and are able to access the database</p>\n<pre><code class=\"lang-auto\">\nUsing cluster file `/var/dynamic-conf/fdb.cluster'.\n\nThe database is available.\n\nWelcome to the fdbcli. For help, type `help'.\n\n</code></pre>\n<p>This doesnt happen in the case if we are running <code>foundationDB</code> as <code>single redundancy mode</code>, in that we just keep getting below error message forever</p>\n<pre><code class=\"lang-auto\">Using cluster file `/var/dynamic-conf/fdb.cluster'.\n\nThe database is unavailable; type `status' for more information.\n\nWelcome to the fdbcli. For help, type `help'.\nfdb&gt; \n</code></pre>\n<p>I hope this would help you debug this issue further.</p>",
        "post_number": 7,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-17T07:35:43.459Z",
        "reply_count": 0,
        "reply_to_post_number": 5,
        "quote_count": 0,
        "incoming_link_count": 6,
        "reads": 48,
        "readers_count": 47,
        "score": 39.6,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "Vivek Singh",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 3,
          "username": "john_brownlee",
          "name": "John Brownlee",
          "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 700,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/7",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 5850,
        "name": "John Brownlee",
        "username": "john_brownlee",
        "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png",
        "created_at": "2019-12-17T15:06:03.064Z",
        "cooked": "<p>Are you able to see logs from the operator, or the describe output from kubectl? The first case looks like it hasn\u2019t completed reconciliation.</p>",
        "post_number": 8,
        "post_type": 1,
        "posts_count": 8,
        "updated_at": "2019-12-17T15:06:03.064Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 44,
        "readers_count": 43,
        "score": 28.8,
        "yours": false,
        "topic_id": 1841,
        "topic_slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
        "display_username": "John Brownlee",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 3,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/connecting-to-the-database-using-fdbcli-results-in-an-error/1841/8",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      5823,
      5824,
      5836,
      5838,
      5839,
      5840,
      5847,
      5850
    ]
  },
  "timeline_lookup": [
    [
      1,
      2139
    ],
    [
      2,
      2137
    ],
    [
      3,
      2136
    ],
    [
      8,
      2135
    ]
  ],
  "suggested_topics": [],
  "tags": [],
  "tags_descriptions": {},
  "fancy_title": "Connecting to the database using `fdbcli` results in an error",
  "id": 1841,
  "title": "Connecting to the database using `fdbcli` results in an error",
  "posts_count": 8,
  "created_at": "2019-12-14T07:23:08.203Z",
  "views": 2426,
  "reply_count": 4,
  "like_count": 0,
  "last_posted_at": "2019-12-17T15:06:03.064Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "connecting-to-the-database-using-fdbcli-results-in-an-error",
  "category_id": 7,
  "word_count": 1086,
  "deleted_at": null,
  "user_id": 700,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": null,
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_1841",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 8,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 2,
  "show_read_indicator": false,
  "thumbnails": null,
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "FoundationDB @ Kubernetes having &ldquo;issues&rdquo;",
      "id": 383,
      "title": "FoundationDB @ Kubernetes having \"issues\"",
      "slug": "foundationdb-kubernetes-having-issues",
      "posts_count": 4,
      "reply_count": 2,
      "highest_post_number": 4,
      "image_url": null,
      "created_at": "2018-05-09T10:17:53.797Z",
      "last_posted_at": "2018-05-11T17:28:05.081Z",
      "bumped": true,
      "bumped_at": "2018-05-11T17:28:05.081Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 2031,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 247,
            "username": "Chr1st0ph",
            "name": "Chr1st0ph",
            "avatar_template": "/user_avatar/forums.foundationdb.org/chr1st0ph/{size}/353_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Trying to make docker image; fdbcli says database not created",
      "id": 157,
      "title": "Trying to make docker image; fdbcli says database not created",
      "slug": "trying-to-make-docker-image-fdbcli-says-database-not-created",
      "posts_count": 8,
      "reply_count": 4,
      "highest_post_number": 8,
      "image_url": null,
      "created_at": "2018-04-20T22:06:18.472Z",
      "last_posted_at": "2019-02-12T13:13:54.630Z",
      "bumped": true,
      "bumped_at": "2019-02-12T13:13:54.630Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 5,
      "views": 3095,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 110,
            "username": "jwatte",
            "name": "Jon Watte",
            "avatar_template": "/user_avatar/forums.foundationdb.org/jwatte/{size}/77_2.png",
            "trust_level": 0
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 8,
            "username": "alloc",
            "name": "Alec Grieser",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alloc/{size}/9_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 22,
            "username": "dave",
            "name": "David Scherer",
            "avatar_template": "/user_avatar/forums.foundationdb.org/dave/{size}/89_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 476,
            "username": "dch",
            "name": "Dave Cottlehuber",
            "avatar_template": "/user_avatar/forums.foundationdb.org/dch/{size}/473_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 506,
            "username": "shane",
            "name": "Shane",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/s/dbc845/{size}.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Error: The database is unavailable",
      "id": 1928,
      "title": "Error: The database is unavailable",
      "slug": "error-the-database-is-unavailable",
      "posts_count": 16,
      "reply_count": 12,
      "highest_post_number": 16,
      "image_url": null,
      "created_at": "2020-02-05T14:11:38.372Z",
      "last_posted_at": "2021-09-30T16:10:23.493Z",
      "bumped": true,
      "bumped_at": "2021-09-30T16:10:23.493Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 2,
      "views": 4282,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 718,
            "username": "Cliicy",
            "name": "Dragon",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/47e85d/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 711,
            "username": "osamarin",
            "name": "Oleg Samarin",
            "avatar_template": "/user_avatar/forums.foundationdb.org/osamarin/{size}/905_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 990,
            "username": "baiwfg2",
            "name": "Lewis Chan",
            "avatar_template": "/user_avatar/forums.foundationdb.org/baiwfg2/{size}/1173_2.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Can not connect to foundationdb docker container",
      "id": 1856,
      "title": "Can not connect to foundationdb docker container",
      "slug": "can-not-connect-to-foundationdb-docker-container",
      "posts_count": 2,
      "reply_count": 0,
      "highest_post_number": 2,
      "image_url": null,
      "created_at": "2019-12-26T14:05:22.848Z",
      "last_posted_at": "2019-12-31T00:12:32.627Z",
      "bumped": true,
      "bumped_at": "2019-12-31T00:12:32.627Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 1550,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 674,
            "username": "ivvist",
            "name": "Victor Istratenko",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/i/da6949/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Errors: Database is unavailable and unable to reach coordination servers on Mac",
      "id": 3967,
      "title": "Errors: Database is unavailable and unable to reach coordination servers on Mac",
      "slug": "errors-database-is-unavailable-and-unable-to-reach-coordination-servers-on-mac",
      "posts_count": 8,
      "reply_count": 6,
      "highest_post_number": 8,
      "image_url": null,
      "created_at": "2023-05-16T06:22:43.435Z",
      "last_posted_at": "2023-05-19T19:42:46.812Z",
      "bumped": true,
      "bumped_at": "2023-05-19T19:42:46.812Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 545,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 1260,
            "username": "joannak-vmware",
            "name": "Joanna Ko",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/j/f475e1/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 454,
            "username": "jzhou",
            "name": "Jingyu Zhou",
            "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
            "admin": true,
            "moderator": true,
            "trust_level": 2
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 700,
        "username": "viveksinghggits",
        "name": "Vivek Singh",
        "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png",
        "post_count": 5,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 3,
        "username": "john_brownlee",
        "name": "John Brownlee",
        "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png",
        "post_count": 3,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "admin": true,
        "trust_level": 4
      }
    ],
    "created_by": {
      "id": 700,
      "username": "viveksinghggits",
      "name": "Vivek Singh",
      "avatar_template": "/user_avatar/forums.foundationdb.org/viveksinghggits/{size}/737_2.png"
    },
    "last_poster": {
      "id": 3,
      "username": "john_brownlee",
      "name": "John Brownlee",
      "avatar_template": "/user_avatar/forums.foundationdb.org/john_brownlee/{size}/22_2.png"
    },
    "links": [
      {
        "url": "https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/config/samples/local_cluster.yaml",
        "title": "fdb-kubernetes-operator/local_cluster.yaml at master \u00b7 FoundationDB/fdb-kubernetes-operator \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 24,
        "user_id": 700,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://kind.sigs.k8s.io/",
        "title": "kind",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 3,
        "user_id": 700,
        "domain": "kind.sigs.k8s.io",
        "root_domain": "k8s.io"
      }
    ]
  },
  "bookmarks": []
}