{
  "post_stream": {
    "posts": [
      {
        "id": 6190,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-13T17:22:53.608Z",
        "cooked": "<h1>Summary</h1>\n<p>Hello all, I\u2019m Kyle over at IBM Cloudant. I\u2019m currently configuring/testing backups/restores against our test infrastructure.</p>\n<p>We use IBM Cloud Object Store (COS) as our blobstore. The FoundationDB cluster itself is not currently configured for intracluster TLS although you will see I\u2019ve provided the necessary TLS configuration to backup CLI commands and backup agents so they can work with IBM COS over TLS. All that is working well and I can trigger backups.</p>\n<p>The issue surfaces when I try to <code>fdbbackup describe</code> or attempt to restore a backup from our blobstore. I\u2019m seeing some kind of permissions error in the logs. They look filesystemy although I\u2019m betting it\u2019s to do with the COS requests. I believe it\u2019s an issue trying to read data back from our store. I can however read objects just fine using the same HMAC API keys configured for backup, but with our <code>ibmcloud</code> CLI tool.</p>\n<p>I\u2019m going to continue troubleshooting \u2013 pull the logs from our COS friends and see if it gives insight into the request against COS that fails. I\u2019ve read through some of the codebase relevant to backup management and most of the dots are connecting, but I\u2019m left stumped as to why we fail to read the snapshot from the blobstore. Any tips on understanding this error are appreciated.</p>\n<h2>Error summary</h2>\n<p>I will restate my test process below but here\u2019s the highlight. Please note that we have some scripts such as <code>sfdbbackup</code> which are just the familiar <code>fdbbackup</code> etc. commands but with TLS/blobcreds flags set. Here\u2019s the kernel for a describe attempt:</p>\n<pre><code class=\"lang-auto\">&lt;Event Severity=\"10\" Time=\"1581545857.363042\" Type=\"BackupContainerDescribe2\" ID=\"0000000000000000\" URL=\"blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups\" LogStartVersionOverride=\"-1\" ExpiredEndVersion=\"-1\" UnreliableEndVersion=\"-1\" LogBeginVersion=\"-1\" LogEndVersion=\"-1\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n&lt;Event Severity=\"30\" Time=\"1581545857.363042\" Type=\"BackupContainerMetadataInvalid\" ID=\"0000000000000000\" URL=\"blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups\" ExpiredEndVersion=\"-1\" UnreliableEndVersion=\"-1\" LogBeginVersion=\"-1\" LogEndVersion=\"-1\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n&lt;Event Severity=\"30\" Time=\"1581545857.479831\" Type=\"AbsolutePathError\" ID=\"0000000000000000\" Path=\"snapshots/snapshot,8016609928,8016609928,42\" UnixErrorCode=\"d\" UnixError=\"Permission denied\" Error=\"platform_error\" ErrorDescription=\"Platform error\" ErrorCode=\"1500\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n&lt;Event Severity=\"40\" Time=\"1581545857.479831\" Type=\"StopAfterError\" ID=\"0000000000000000\" Error=\"platform_error\" ErrorDescription=\"Platform error\" ErrorCode=\"1500\" Backtrace=\"addr2line -e fdbbackup.debug -p -C -f -i 0xaa1d3f 0xaa114f 0x4d74c3 0x4d76ae 0x4f8349 0x4cd4f1 0x4cd66e 0x5b3441 0x5b38e1 0x4f8349 0x4f8349 0x593fde 0x5be1d9 0x42851c 0x5b7990 0x5e0f15 0x5e1047 0x5d9551 0x4fa0f8 0x5e9785 0x5eaced 0x5eafa1 0x5e51f8 0x5e5497 0x5e575c 0x5e0ab8 0x75d87f 0x75e0c1 0x75bd00 0x75ce57 0x75d083 0x75d11c 0x75b190 0x75ba8d 0x4fa0f8 0x4cd15f 0x75aad8 0x75bc0f 0x4fa060 0xae4660 0x8391ea 0x4b6e5d 0x7f69703fc2e1\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n</code></pre>\n<p>Here is the API key reading that object just fine:</p>\n<pre><code class=\"lang-auto\">ibmcloud cos config list\nKey                     Value   \nLast Updated            Wednesday, February 12 2020 at 16:11:14   \nDefault Region          us-south   \nDownload Location       /Users/ksnavely@us.ibm.com/Downloads   \nCRN                        \nAccessKeyID             936027fd996b447197a674452f421752   \nSecretAccessKey         ************************************************   \nAuthentication Method   HMAC   \nURL Style               VHost   \n\nibmcloud cos get-object --bucket cloudant-wp2-backups --key 'data/ktest-feb-12-01/snapshots/snapshot,8016609928,8016609928,42' get_test\nOK\nSuccessfully downloaded 'data/ktest-feb-12-01/snapshots/snapshot,8016609928,8016609928,42' from bucket 'cloudant-wp2-backups'\n176 B downloaded.\n</code></pre>\n<h2>Testing process</h2>\n<p>What follows is the complete process of my attempt to <code>describe</code> a backup. Restores fail in the same way.</p>\n<p>First, seed a key/value.</p>\n<pre><code class=\"lang-auto\">fdb&gt; writemode on\nfdb&gt; get ktest\n`ktest': not found\nfdb&gt; set ktest foo\nCommitted (7575052530)\n</code></pre>\n<p>Next, start a backup covering this keyrange.</p>\n<pre><code class=\"lang-auto\">sudo -u foundationdb sfdbbackup start -d 'blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups&amp;sc=1' --log -t ktest-feb-12-01 -k \"ktest ktest/xff\"\nThe backup on tag `ktest-feb-12-01' was successfully submitted.\n</code></pre>\n<p>There were no errors in the trace logs for the above command. I checked the status:</p>\n<pre><code class=\"lang-auto\">fdbbackup status -t ktest-feb-12-01\nThe previous backup on tag `ktest-feb-12-01' at blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups&amp;sc=1 completed at version 8036461619.\nBackupUID: a6cef066c8e245fff9eb2a3fd651bd84\nBackupURL: blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups&amp;sc=1\n</code></pre>\n<p>It had completed quickly as expected.</p>\n<p>I next pulled all the logs for all backup agents from all cluster nodes. I could not find any error or metadata information in the logs. All I see is a brief few logs denoting success of the ktest backup.</p>\n<p>Next I inspect the state of the backup.</p>\n<pre><code class=\"lang-auto\">sudo -u foundationdb sfdbbackup list -b 'blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/?bucket=cloudant-wp2-backups&amp;sc=1'\nblobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups\n\nsudo -u foundationdb sfdbbackup describe -d blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups -C /etc/foundationdb/fdb.cluster --log\nERROR: Platform error\nFatal Error: Platform error\n</code></pre>\n<p>The logs from the <code>describe</code> attempt:</p>\n<pre><code class=\"lang-auto\">&lt;Event Severity=\"10\" Time=\"1581545857.236408\" Type=\"BlobStoreEndpointReusingConnected\" ID=\"0000000000000000\" SuppressedEventCount=\"0\" RemoteEndpoint=\"10.1.129.83:443:tls\" ExpiresIn=\"119.88\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n&lt;Event Severity=\"10\" Time=\"1581545857.363042\" Type=\"BackupContainerDescribe2\" ID=\"0000000000000000\" URL=\"blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups\" LogStartVersionOverride=\"-1\" ExpiredEndVersion=\"-1\" UnreliableEndVersion=\"-1\" LogBeginVersion=\"-1\" LogEndVersion=\"-1\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n&lt;Event Severity=\"30\" Time=\"1581545857.363042\" Type=\"BackupContainerMetadataInvalid\" ID=\"0000000000000000\" URL=\"blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-12-01?bucket=cloudant-wp2-backups\" ExpiredEndVersion=\"-1\" UnreliableEndVersion=\"-1\" LogBeginVersion=\"-1\" LogEndVersion=\"-1\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n&lt;Event Severity=\"30\" Time=\"1581545857.479831\" Type=\"AbsolutePathError\" ID=\"0000000000000000\" Path=\"snapshots/snapshot,8016609928,8016609928,42\" UnixErrorCode=\"d\" UnixError=\"Permission denied\" Error=\"platform_error\" ErrorDescription=\"Platform error\" ErrorCode=\"1500\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n&lt;Event Severity=\"40\" Time=\"1581545857.479831\" Type=\"StopAfterError\" ID=\"0000000000000000\" Error=\"platform_error\" ErrorDescription=\"Platform error\" ErrorCode=\"1500\" Backtrace=\"addr2line -e fdbbackup.debug -p -C -f -i 0xaa1d3f 0xaa114f 0x4d74c3 0x4d76ae 0x4f8349 0x4cd4f1 0x4cd66e 0x5b3441 0x5b38e1 0x4f8349 0x4f8349 0x593fde 0x5be1d9 0x42851c 0x5b7990 0x5e0f15 0x5e1047 0x5d9551 0x4fa0f8 0x5e9785 0x5eaced 0x5eafa1 0x5e51f8 0x5e5497 0x5e575c 0x5e0ab8 0x75d87f 0x75e0c1 0x75bd00 0x75ce57 0x75d083 0x75d11c 0x75b190 0x75ba8d 0x4fa0f8 0x4cd15f 0x75aad8 0x75bc0f 0x4fa060 0xae4660 0x8391ea 0x4b6e5d 0x7f69703fc2e1\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt;\n</code></pre>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-13T17:22:53.608Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 200,
        "reads": 49,
        "readers_count": 48,
        "score": 1004.8,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://forums.foundationdb.org/t/how-to-run-fdbbackup-against-cos/3298/2",
            "internal": true,
            "reflection": true,
            "title": "How to run fdbbackup against COS\uff1f",
            "clicks": 0
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 6191,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-13T17:25:24.311Z",
        "cooked": "<p>By the way, we are using FoundationDB 6.2.10.</p>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-13T17:25:24.311Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 43,
        "readers_count": 42,
        "score": 18.6,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6204,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-02-14T04:01:57.419Z",
        "cooked": "<p>First thing to try is your describe command again with <code>--knob_http_verbose_level=2</code> which will print the HTTPS requests and responses to standard output.</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-14T04:01:57.419Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 40,
        "readers_count": 39,
        "score": 13.0,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6205,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-02-14T04:06:01.091Z",
        "cooked": "<p>Just an FYI, the <code>BackupContainerMetadataInvalid</code> trace event is not actually a problem in this situation.  It is referring to metadata which is populated and updated incrementally by backup management commands such as <code>describe</code> and <code>expire</code>.  This metadata describes version ranges of files which are either known to have been complete at some point in time or known to potentially be incomplete, and this allows describe commands to not have to list/scan the eventual millions of files a backup will contain during each backup management operation, as that would take a long time.</p>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-14T04:06:46.399Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 42,
        "readers_count": 41,
        "score": 8.4,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6206,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-02-14T04:13:23.523Z",
        "cooked": "<p>My guess as to what is happening here is the blob requests are working fine but something in the blob backup destination code is using a function in Platform.cpp called  <code>abspath()</code> for convenience, while not expecting the path to actually exist on disk.  I can\u2019t actually find a code path that does this, but the logs are evidence that there is one.</p>\n<p>Might there be an unreadable <code>snapshots</code> folder in <code>fdbbackup</code>'s working directory?</p>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-14T04:18:06.200Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 42,
        "readers_count": 41,
        "score": 8.4,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6232,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-17T16:58:07.258Z",
        "cooked": "<p>Steve thank you for your response. I\u2019d forgotten all about that HTTP verboseness knob!</p>\n<p>To add some intrigue to the mix the IBM COS folks are saying they can\u2019t find e.g. a 403 in our access logs. I\u2019ll revisit this as soon as I\u2019m able and share more information.</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-17T16:58:07.258Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 39,
        "readers_count": 38,
        "score": 7.8,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6247,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-18T22:42:25.675Z",
        "cooked": "<aside class=\"quote no-group quote-modified\" data-username=\"SteavedHams\" data-post=\"3\" data-topic=\"1944\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/steavedhams/48/18_2.png\" class=\"avatar\"> SteavedHams:</div>\n<blockquote>\n<p>\u2013knob_http_verbose_level=2</p>\n</blockquote>\n</aside>\n<p>That was great to be reminded of.</p>\n<pre><code class=\"lang-auto\">sudo -u foundationdb sfdbbackup start -d 'blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-18-01?bucket=cloudant-wp2-backups&amp;sc=1' --log -t ktest-feb-18-01 -k \"ktest ktest/xff\"\nThe backup on tag `ktest-feb-18-01' was successfully submitted.\n</code></pre>\n<pre><code class=\"lang-auto\">sudo -u foundationdb sfdbbackup describe -d blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-18-01?bucket=cloudant-wp2-backups -C /etc/foundationdb/fdb.cluster --log --knob_http_verbose_level=2\n[a733810bc81535efcc61efad34748808] HTTP starting HEAD /cloudant-wp2-backups/backups/ktest-feb-18-01 ContentLen:0\n[a733810bc81535efcc61efad34748808] HTTP code=200 early=0, time=0.103528s HEAD /cloudant-wp2-backups/backups/ktest-feb-18-01 contentLen=0 [277 out, response content len 0]\n[a733810bc81535efcc61efad34748808] HTTP starting HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/expired_end_version ContentLen:0\n[7f0345d1b2675c981a9798e11597e2d0] HTTP starting HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/log_end_version ContentLen:0\n[15dd7e7d000b425d2eefadd0857a8a1d] HTTP starting HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/log_begin_version ContentLen:0\n[de0061b79bebbf4b8486eee0c52584f7] HTTP starting HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/unreliable_end_version ContentLen:0\n[15dd7e7d000b425d2eefadd0857a8a1d] HTTP code=404 early=0, time=0.075547s HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/log_begin_version contentLen=0 [303 out, response content len 331]\n[7f0345d1b2675c981a9798e11597e2d0] HTTP code=404 early=0, time=0.083543s HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/log_end_version contentLen=0 [301 out, response content len 329]\n[de0061b79bebbf4b8486eee0c52584f7] HTTP code=404 early=0, time=0.174761s HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/unreliable_end_version contentLen=0 [308 out, response content len 336]\n[a733810bc81535efcc61efad34748808] HTTP code=404 early=0, time=0.435969s HEAD /cloudant-wp2-backups/data/ktest-feb-18-01/properties/expired_end_version contentLen=0 [305 out, response content len 333]\n[15dd7e7d000b425d2eefadd0857a8a1d] HTTP starting GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/snapshots/&amp;delimiter=/&amp;marker= ContentLen:0\n[7f0345d1b2675c981a9798e11597e2d0] HTTP starting GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/logs/&amp;delimiter=/&amp;marker= ContentLen:0\n[7f0345d1b2675c981a9798e11597e2d0] HTTP code=200 early=0, time=0.006408s GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/logs/&amp;delimiter=/&amp;marker= contentLen=0 [321 out, response content len 393]\n[de0061b79bebbf4b8486eee0c52584f7] HTTP starting GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/logs/0000/&amp;delimiter=/&amp;marker= ContentLen:0\n[de0061b79bebbf4b8486eee0c52584f7] HTTP code=200 early=0, time=0.063112s GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/logs/0000/&amp;delimiter=/&amp;marker= contentLen=0 [326 out, response content len 403]\n[a733810bc81535efcc61efad34748808] HTTP starting GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/logs/0000/0000/&amp;delimiter=/&amp;marker= ContentLen:0\n[15dd7e7d000b425d2eefadd0857a8a1d] HTTP code=200 early=0, time=0.080596s GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/snapshots/&amp;delimiter=/&amp;marker= contentLen=0 [326 out, response content len 701]\n[a733810bc81535efcc61efad34748808] HTTP *ERROR*=operation_cancelled early=0, time=0.011054s GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/logs/0000/0000/&amp;delimiter=/&amp;marker= contentLen=0 [331 out]\nERROR: Platform error\nFatal Error: Platform error\n</code></pre>\n<p>I\u2019m just looking into this new message. It looks like <code>GET /cloudant-wp2-backups/?max-keys=1000&amp;prefix=data/ktest-feb-18-01/logs/0000/0000/&amp;delimiter=/&amp;marker=</code> is cancelled after 11ms?</p>\n<p>I performed similar commands with our IBM Cloud CLI tool.</p>\n<pre><code class=\"lang-auto\">ic cos list-objects --bucket cloudant-wp2-backups --max-items 10 --page-size 20 --prefix 'data/ktest-feb-18-01/logs/0000/0000' --delimiter '' --marker ''\nOK\nFound 1 object in bucket 'cloudant-wp2-backups':\n\nName                                                                                                       Last Modified              Object Size   \ndata/ktest-feb-18-01/logs/0000/0000/log,81944689829,81964689829,6dafb1ab8a0370b35d513aaf10e3d307,1048576   Feb 18, 2020 at 22:18:18   0 B   \n</code></pre>\n<p>From the verbose logs for that command I can see the successful request:</p>\n<pre><code class=\"lang-auto\">REQUEST: [2020-02-18T15:36:47-07:00]\nGET /?delimiter=&amp;marker=&amp;max-keys=10&amp;prefix=data%2Fktest-feb-18-01%2Flogs%2F0000%2F0000 HTTP/1.1\nHost: cloudant-wp2-backups.s3.us-south.cloud-object-storage.appdomain.cloud\n...\nRESPONSE: [2020-02-18T15:36:48-07:00] Elapsed: 338ms\nHTTP/1.1 200 OK\n</code></pre>\n<p>I\u2019ll keep thinking on this one. The 404\u2019s for <code>data/ktest-feb-18-01/properties/</code> data, is that OK with the client?</p>",
        "post_number": 7,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T22:42:25.675Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 1,
        "incoming_link_count": 1,
        "reads": 35,
        "readers_count": 34,
        "score": 17.0,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/7",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6248,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-18T22:48:59.132Z",
        "cooked": "<p>Oh also, no there is no local snapshots directory.</p>",
        "post_number": 8,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T22:48:59.132Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 32,
        "readers_count": 31,
        "score": 26.4,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/8",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6249,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-02-18T22:56:58.614Z",
        "cooked": "<p>The request is being canceled because something is encountering a platform error exception which is being handled at the outermost level, which cancels the program execution and stops all in-progress operations.  As I said before, something is calling absPath(), but I\u2019m not sure what that is.  You can see from this trace event</p>\n<p><code>&lt;Event Severity=\"30\" Time=\"1581545857.479831\" Type=\"AbsolutePathError\" ID=\"0000000000000000\" Path=\"snapshots/snapshot,8016609928,8016609928,42\" UnixErrorCode=\"d\" UnixError=\"Permission denied\" Error=\"platform_error\" ErrorDescription=\"Platform error\" ErrorCode=\"1500\" Machine=\"0.0.0.0:0\" LogGroup=\"\" /&gt; </code><br>\nthat something is calling abspath() with a backup file path, and that\u2019s resulting in a platform error.</p>\n<p>I can\u2019t find a code path that could lead to this.</p>\n<p>Is the working directory perhaps not listable or readable by the user running the process?</p>",
        "post_number": 9,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T22:56:58.614Z",
        "reply_count": 0,
        "reply_to_post_number": 7,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 32,
        "readers_count": 31,
        "score": 11.4,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "reply_to_user": {
          "id": 484,
          "username": "ksnavely",
          "name": "Kyle Snavely",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/9",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6250,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-02-18T23:07:55.936Z",
        "cooked": "<p>I found the issue.</p>\n<p>BackupContainerFileSystem, the parent class of BackupContainerBlobStore, uses a method called basename() in several places to extract a filename from a path string, and basename() uses abspath(), which first normalizes the given path using abspath().</p>\n<p>Obviously it makes no sense to look for remote paths on the local filesystem, basename() was just being used as a convenience because it also works for paths that do not exist at all.  But I\u2019m guessing it throws a platform error if something in the path does exist but just isn\u2019t readable.</p>",
        "post_number": 10,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T23:07:55.936Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 6,
        "reads": 32,
        "readers_count": 31,
        "score": 36.4,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/10",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6251,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-18T23:07:58.960Z",
        "cooked": "<p>Here\u2019s the local permissions layout. The <code>foundationdb</code> user is used to run the commands due to secrets file ownership (the <code>sfdbbackup</code> alias).</p>\n<p>My working dir for a describe attempt should be wide open.</p>\n<pre><code class=\"lang-auto\">ls -alh .\ntotal 16K\ndrwxrwxrwx 2 foundationdb foundationdb 4.0K Feb 18 23:01 .\ndrwxrwxrwx 3 foundationdb foundationdb 4.0K Feb 18 23:00 ..\n-rw-r--r-- 1 foundationdb foundationdb 6.5K Feb 18 23:01 trace.0.0.0.0.0.1582066875.WRkUFF.0.1.xml\n</code></pre>",
        "post_number": 11,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T23:07:58.960Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 30,
        "readers_count": 29,
        "score": 6.0,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/11",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6252,
        "name": "Alex Miller",
        "username": "alexmiller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "created_at": "2020-02-18T23:31:09.316Z",
        "cooked": "<aside class=\"quote no-group quote-modified\" data-username=\"ksnavely\" data-post=\"1\" data-topic=\"1944\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/ksnavely/48/483_2.png\" class=\"avatar\"> ksnavely:</div>\n<blockquote>\n<p>&lt;Event Severity=\u201c40\u201d Time=\u201c1581545857.479831\u201d Type=\u201cStopAfterError\u201d ID=\u201c0000000000000000\u201d Error=\u201cplatform_error\u201d ErrorDescription=\u201cPlatform error\u201d ErrorCode=\u201c1500\u201d Backtrace=Yes</p>\n</blockquote>\n</aside>\n<aside class=\"quote no-group\" data-username=\"ksnavely\" data-post=\"2\" data-topic=\"1944\" data-full=\"true\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/ksnavely/48/483_2.png\" class=\"avatar\"> ksnavely:</div>\n<blockquote>\n<p>By the way, we are using FoundationDB 6.2.10.</p>\n</blockquote>\n</aside>\n<p>These were the important bits.  Thanks!</p>\n<p>Symbolicated backtrace at <a href=\"https://gist.github.com/alexmiller-apple/07ab8d3199f3629c23628eba911c1743\" class=\"inline-onebox\">fdbbackup stacktrace \u00b7 GitHub</a></p>\n<p><a class=\"mention\" href=\"/u/steavedhams\">@SteavedHams</a> It looks like he ends up in BackupContainerFileSystem::listKeyspaceSnapshots, and <code>listKeyspaceSnapshots</code> calls <code>pathToKeyspaceSnapshotFile</code> which calls <code>basename</code>, which calls <code>abspath</code>.</p>\n<p>EDIT: ARRRGH YOU BEAT ME</p>",
        "post_number": 12,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T23:31:35.030Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 2,
        "incoming_link_count": 0,
        "reads": 28,
        "readers_count": 27,
        "score": 5.6,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Alex Miller",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://gist.github.com/alexmiller-apple/07ab8d3199f3629c23628eba911c1743",
            "internal": false,
            "reflection": false,
            "title": "fdbbackup stacktrace \u00b7 GitHub",
            "clicks": 1
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 13,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/12",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6253,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-18T23:33:34.081Z",
        "cooked": "<p>I see so looking around here regarding the actual but unintended filesystem check: <a href=\"https://github.com/apple/foundationdb/blame/a41aa41816ec21351a1b823d2f8814a3db52757d/flow/Platform.cpp#L1976\" rel=\"nofollow noopener\">https://github.com/apple/foundationdb/blame/a41aa41816ec21351a1b823d2f8814a3db52757d/flow/Platform.cpp#L1976</a> For the 6.2 release anyways.</p>\n<p>Yes we need to get the debug symbol binaries in common usage here. We\u2019ve been using the Ubuntu .debs which don\u2019t have these the last I checked.</p>",
        "post_number": 13,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T23:33:34.081Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 6,
        "reads": 28,
        "readers_count": 27,
        "score": 40.6,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/blame/a41aa41816ec21351a1b823d2f8814a3db52757d/flow/Platform.cpp#L1976",
            "internal": false,
            "reflection": false,
            "title": "foundationdb/flow/Platform.cpp at a41aa41816ec21351a1b823d2f8814a3db52757d \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 2
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/13",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6254,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-18T23:33:50.684Z",
        "cooked": "<p>I\u2019m just surprised I\u2019m the first to see this I suppose.</p>",
        "post_number": 14,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-18T23:33:50.684Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 29,
        "readers_count": 28,
        "score": 5.8,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/14",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6255,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-19T00:17:34.672Z",
        "cooked": "<p>Alright I know why I\u2019m special. Even though the working dir and parent dir were accessible to the <code>foundationdb</code> user, they still were in my home directory.</p>\n<p>To change things, I ran this test from a directory where the <code>foundationdb</code> user was able to read everything from / to the workdir and I had a successful <code>describe</code>.</p>\n<pre><code class=\"lang-auto\">sudo -u foundationdb sfdbbackup describe -d blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-18-01?bucket=cloudant-wp2-backups -C /etc/foundationdb/fdb.cluster --log \nURL: blobstore://936027fd996b447197a674452f421752@s3.private.us-south.cloud-object-storage.appdomain.cloud/ktest-feb-18-01?bucket=cloudant-wp2-backups\nRestorable: true\nSnapshot:  startVersion=81944848101 (maxLogEnd -0.00 days)  endVersion=81944848101 (maxLogEnd -0.00 days)  totalBytes=42  restorable=true  expiredPct=0.00\nSnapshotBytes: 42\nMinLogBeginVersion:      81944689829 (maxLogEnd -0.00 days)\nContiguousLogEndVersion: 81964689829 (maxLogEnd -0.00 days)\nMaxLogEndVersion:        81964689829 (maxLogEnd -0.00 days)\nMinRestorableVersion:    81944848101 (maxLogEnd -0.00 days)\nMaxRestorableVersion:    81964689828 (maxLogEnd -0.00 days)\n</code></pre>",
        "post_number": 15,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-19T00:18:35.466Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 29,
        "readers_count": 28,
        "score": 5.8,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/15",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6256,
        "name": "Alex Miller",
        "username": "alexmiller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "created_at": "2020-02-19T00:19:58.149Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"ksnavely\" data-post=\"13\" data-topic=\"1944\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/ksnavely/48/483_2.png\" class=\"avatar\"> ksnavely:</div>\n<blockquote>\n<p>Yes we need to get the debug symbol binaries in common usage here.</p>\n</blockquote>\n</aside>\n<p>If you hadn\u2019t already seen, on the <a href=\"https://www.foundationdb.org/download/\">Downloads page</a>, there\u2019s a fdb_$version-debug.tar.gz.  Copy the URL, and edit it to the right version, and the tarball should still be there for any previously published version.</p>",
        "post_number": 16,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-19T00:19:58.149Z",
        "reply_count": 0,
        "reply_to_post_number": 13,
        "quote_count": 1,
        "incoming_link_count": 0,
        "reads": 28,
        "readers_count": 27,
        "score": 5.6,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Alex Miller",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://www.foundationdb.org/download/",
            "internal": false,
            "reflection": false,
            "title": "FoundationDB | Download",
            "clicks": 2
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 13,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/16",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6257,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-19T00:31:12.361Z",
        "cooked": "<p>Ah nice, that\u2019s a great tip.</p>\n<p>Would you guys like me to file a bug for this remote-blobstore local-fs check behavior?</p>",
        "post_number": 17,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-19T00:31:12.361Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 25,
        "readers_count": 24,
        "score": 10.0,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/17",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6258,
        "name": "Kyle Snavely",
        "username": "ksnavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "created_at": "2020-02-19T00:33:34.262Z",
        "cooked": "<p>I\u2019ve confirmed using a workdir path where all dirs in the path can been x/r\u2019d by the <code>foundationdb</code> user fixes my issue for remote blobstore restore as well.</p>",
        "post_number": 18,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-19T00:33:34.262Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 25,
        "readers_count": 24,
        "score": 15.0,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Kyle Snavely",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 484,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/18",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6259,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-02-19T00:38:01.043Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"ksnavely\" data-post=\"17\" data-topic=\"1944\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/ksnavely/48/483_2.png\" class=\"avatar\"> ksnavely:</div>\n<blockquote>\n<p>Would you guys like me to file a bug for this remote-blobstore local-fs check behavior?</p>\n</blockquote>\n</aside>\n<p>I\u2019ve already fixed it by replacing basename with a pure string manipulation that handles both slash types.</p>\n<aside class=\"onebox githubpullrequest\" data-onebox-src=\"https://github.com/apple/foundationdb/pull/2693\">\n  <header class=\"source\">\n\n      <a href=\"https://github.com/apple/foundationdb/pull/2693\" target=\"_blank\" rel=\"noopener\">github.com/apple/foundationdb</a>\n  </header>\n\n  <article class=\"onebox-body\">\n    <div class=\"github-row\">\n\n\n\n    <div class=\"github-icon-container\" title=\"Pull Request\">\n      <svg width=\"60\" height=\"60\" class=\"github-icon\" viewBox=\"0 0 12 16\" aria-hidden=\"true\"><path fill-rule=\"evenodd\" d=\"M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0 0 10 15a1.993 1.993 0 0 0 1-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 0 0-1 3.72v6.56A1.993 1.993 0 0 0 2 15a1.993 1.993 0 0 0 1-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z\"></path></svg>\n    </div>\n\n  <div class=\"github-info-container\">\n\n\n\n      <h4>\n        <a href=\"https://github.com/apple/foundationdb/pull/2693\" target=\"_blank\" rel=\"noopener\">BackupContainerFilesystem no longer unnecessarily depends on abspath()..</a>\n      </h4>\n\n    <div class=\"branches\">\n      <code>apple:release-6.2</code> \u2190 <code>satherton:fix-backup-basename-issue</code>\n    </div>\n\n      <div class=\"github-info\">\n        <div class=\"date\">\n          opened <span class=\"discourse-local-date\" data-format=\"ll\" data-date=\"2020-02-19\" data-time=\"00:37:19\" data-timezone=\"UTC\">12:37AM - 19 Feb 20 UTC</span>\n        </div>\n\n        <div class=\"user\">\n          <a href=\"https://github.com/satherton\" target=\"_blank\" rel=\"noopener\">\n            <img alt=\"satherton\" src=\"https://global.discourse-cdn.com/foundationdb/original/2X/2/2c3d006fbcd90afbe45c131d050d571b259a8a43.png\" class=\"onebox-avatar-inline\" width=\"20\" height=\"20\" data-dominant-color=\"5A6257\">\n            satherton\n          </a>\n        </div>\n\n        <div class=\"lines\" title=\"2 commits changed 2 files with 19 additions and 3 deletions\">\n          <a href=\"https://github.com/apple/foundationdb/pull/2693/files\" target=\"_blank\" rel=\"noopener\">\n            <span class=\"added\">+19</span>\n            <span class=\"removed\">-3</span>\n          </a>\n        </div>\n      </div>\n  </div>\n</div>\n\n  <div class=\"github-row\">\n    <p class=\"github-body-container\">\u2026 to find the last part of a path string, since it shouldn't touch the local fil<span class=\"show-more-container\"><a href=\"https://github.com/apple/foundationdb/pull/2693\" target=\"_blank\" rel=\"noopener\" class=\"show-more\">\u2026</a></span><span class=\"excerpt hidden\">esystem in the remote case.</span></p>\n  </div>\n\n  </article>\n\n  <div class=\"onebox-metadata\">\n    \n    \n  </div>\n\n  <div style=\"clear: both\"></div>\n</aside>\n",
        "post_number": 19,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-19T00:39:10.740Z",
        "reply_count": 0,
        "reply_to_post_number": 17,
        "quote_count": 1,
        "incoming_link_count": 2,
        "reads": 26,
        "readers_count": 25,
        "score": 15.2,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/pull/2693",
            "internal": false,
            "reflection": false,
            "title": "BackupContainerFilesystem no longer unnecessarily depends on abspath().. by satherton \u00b7 Pull Request #2693 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 4
          }
        ],
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/19",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6260,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-02-19T00:40:20.641Z",
        "cooked": "<p>Glad you found a way to avoid the issue for now.  The next release will have it fixed.</p>",
        "post_number": 20,
        "post_type": 1,
        "posts_count": 20,
        "updated_at": "2020-02-19T00:40:20.641Z",
        "reply_count": 0,
        "reply_to_post_number": 18,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 26,
        "readers_count": 25,
        "score": 20.2,
        "yours": false,
        "topic_id": 1944,
        "topic_slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "reply_to_user": {
          "id": 484,
          "username": "ksnavely",
          "name": "Kyle Snavely",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png"
        },
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 1
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors/1944/20",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      6190,
      6191,
      6204,
      6205,
      6206,
      6232,
      6247,
      6248,
      6249,
      6250,
      6251,
      6252,
      6253,
      6254,
      6255,
      6256,
      6257,
      6258,
      6259,
      6260
    ]
  },
  "timeline_lookup": [
    [
      1,
      2077
    ],
    [
      6,
      2073
    ],
    [
      7,
      2072
    ]
  ],
  "suggested_topics": [],
  "tags": [],
  "tags_descriptions": {},
  "fancy_title": "Sanity check: FoundationDB backup blobstore credentials permissions errors",
  "id": 1944,
  "title": "Sanity check: FoundationDB backup blobstore credentials permissions errors",
  "posts_count": 20,
  "created_at": "2020-02-13T17:22:53.536Z",
  "views": 1493,
  "reply_count": 4,
  "like_count": 1,
  "last_posted_at": "2020-02-19T00:40:20.641Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
  "category_id": 7,
  "word_count": 2930,
  "deleted_at": null,
  "user_id": 484,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": null,
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_1944",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 20,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 3,
  "show_read_indicator": false,
  "thumbnails": null,
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "Fdbbackup expire with blobstore returning error, not deleting from S3",
      "id": 1131,
      "title": "Fdbbackup expire with blobstore returning error, not deleting from S3",
      "slug": "fdbbackup-expire-with-blobstore-returning-error-not-deleting-from-s3",
      "posts_count": 19,
      "reply_count": 11,
      "highest_post_number": 19,
      "image_url": "https://global.discourse-cdn.com/foundationdb/optimized/1X/dc9b21297880928293b7194125f1889c26a4f70a_2_1024x579.png",
      "created_at": "2019-02-12T22:55:17.346Z",
      "last_posted_at": "2020-01-24T13:25:04.572Z",
      "bumped": true,
      "bumped_at": "2020-01-24T13:25:04.572Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 2,
      "views": 2227,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 490,
            "username": "rjenkins",
            "name": "Ray Jenkins",
            "avatar_template": "/user_avatar/forums.foundationdb.org/rjenkins/{size}/487_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 337,
            "username": "mengxu",
            "name": "Meng Xu",
            "avatar_template": "/user_avatar/forums.foundationdb.org/mengxu/{size}/893_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 7,
            "username": "SteavedHams",
            "name": "Steve Atherton",
            "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 634,
            "username": "somu",
            "name": "somasundaram",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/s/ce73a5/{size}.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "[RESOLVED?] Fdbbackup &lsquo;Platform error&rsquo; on &lsquo;file_backup_write_range&rsquo;",
      "id": 412,
      "title": "[RESOLVED?] Fdbbackup 'Platform error' on 'file_backup_write_range'",
      "slug": "resolved-fdbbackup-platform-error-on-file-backup-write-range",
      "posts_count": 9,
      "reply_count": 6,
      "highest_post_number": 9,
      "image_url": null,
      "created_at": "2018-05-14T13:43:20.133Z",
      "last_posted_at": "2018-05-17T00:24:36.294Z",
      "bumped": true,
      "bumped_at": "2018-05-17T00:24:36.294Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 2465,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 187,
            "username": "hiroshi",
            "name": "",
            "avatar_template": "/user_avatar/forums.foundationdb.org/hiroshi/{size}/147_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 7,
            "username": "SteavedHams",
            "name": "Steve Atherton",
            "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Fdbbackup to blobstore failed using blob_credentials",
      "id": 2794,
      "title": "Fdbbackup to blobstore failed using blob_credentials",
      "slug": "fdbbackup-to-blobstore-failed-using-blob-credentials",
      "posts_count": 1,
      "reply_count": 0,
      "highest_post_number": 1,
      "image_url": null,
      "created_at": "2021-07-16T02:42:49.849Z",
      "last_posted_at": "2021-07-16T02:42:49.932Z",
      "bumped": true,
      "bumped_at": "2021-07-16T06:52:52.308Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 481,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest single",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 965,
            "username": "boorishwreck",
            "name": "",
            "avatar_template": "/user_avatar/forums.foundationdb.org/boorishwreck/{size}/1135_2.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "FoundationDB fdbbackup",
      "id": 1460,
      "title": "FoundationDB fdbbackup",
      "slug": "foundationdb-fdbbackup",
      "posts_count": 7,
      "reply_count": 2,
      "highest_post_number": 7,
      "image_url": null,
      "created_at": "2019-06-17T18:54:47.516Z",
      "last_posted_at": "2019-10-09T03:07:15.974Z",
      "bumped": true,
      "bumped_at": "2019-10-09T03:07:15.974Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 2461,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 579,
            "username": "approachcp",
            "name": "",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/f04885/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 581,
            "username": "surprisetalk",
            "name": "Taylor Sarrafian",
            "avatar_template": "/user_avatar/forums.foundationdb.org/surprisetalk/{size}/579_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 7,
            "username": "SteavedHams",
            "name": "Steve Atherton",
            "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "FoundatioDBBackup against azure blobstore - unknown error",
      "id": 2404,
      "title": "FoundatioDBBackup against azure blobstore - unknown error",
      "slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
      "posts_count": 15,
      "reply_count": 10,
      "highest_post_number": 15,
      "image_url": null,
      "created_at": "2020-10-22T08:10:38.576Z",
      "last_posted_at": "2022-06-27T18:32:25.783Z",
      "bumped": true,
      "bumped_at": "2022-06-27T18:32:25.783Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 8,
      "views": 1476,
      "category_id": 16,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 746,
            "username": "matiasholte",
            "name": "Matias Holte",
            "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 7,
            "username": "SteavedHams",
            "name": "Steve Atherton",
            "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 837,
            "username": "petr-tichy",
            "name": "Petr Tich\u00fd",
            "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 405,
            "username": "harikb",
            "name": "Hari B",
            "avatar_template": "/user_avatar/forums.foundationdb.org/harikb/{size}/1033_2.png",
            "trust_level": 2
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 484,
        "username": "ksnavely",
        "name": "Kyle Snavely",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
        "post_count": 11,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 7,
        "username": "SteavedHams",
        "name": "Steve Atherton",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "post_count": 7,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 4
      },
      {
        "id": 13,
        "username": "alexmiller",
        "name": "Alex Miller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "post_count": 2,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 4
      }
    ],
    "created_by": {
      "id": 484,
      "username": "ksnavely",
      "name": "Kyle Snavely",
      "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png"
    },
    "last_poster": {
      "id": 7,
      "username": "SteavedHams",
      "name": "Steve Atherton",
      "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png"
    },
    "links": [
      {
        "url": "https://github.com/apple/foundationdb/pull/2693",
        "title": "BackupContainerFilesystem no longer unnecessarily depends on abspath().. by satherton \u00b7 Pull Request #2693 \u00b7 apple/foundationdb \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 4,
        "user_id": 7,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://github.com/apple/foundationdb/blame/a41aa41816ec21351a1b823d2f8814a3db52757d/flow/Platform.cpp#L1976",
        "title": "foundationdb/flow/Platform.cpp at a41aa41816ec21351a1b823d2f8814a3db52757d \u00b7 apple/foundationdb \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 2,
        "user_id": 484,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://www.foundationdb.org/download/",
        "title": "FoundationDB | Download",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 2,
        "user_id": 13,
        "domain": "www.foundationdb.org",
        "root_domain": "foundationdb.org"
      },
      {
        "url": "https://gist.github.com/alexmiller-apple/07ab8d3199f3629c23628eba911c1743",
        "title": "fdbbackup stacktrace \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 1,
        "user_id": 13,
        "domain": "gist.github.com",
        "root_domain": "github.com"
      }
    ]
  },
  "bookmarks": []
}