{
  "post_stream": {
    "posts": [
      {
        "id": 8135,
        "name": "Matias Holte",
        "username": "matiasholte",
        "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png",
        "created_at": "2020-10-22T08:10:38.670Z",
        "cooked": "<p>I\u2019m trying to set up backup to azure blobstore through a minIO gateway, but when I run<br>\n<code>root@foundationdb-cluster-backup-agents-7f47c7986b-6z259:/var/fdb# fdbbackup start -d 'blobstore://timelordsfdbtest@minio-gateway-service:9000/testbackup?sc=0&amp;bucket=testbucket' --log --trace_format json --knob_http_verbose_level=3</code><br>\nI get<br>\n<code>ERROR: Could not create backup container: Operation timed out</code><br>\n<code>ERROR: An error was encountered during submission</code><br>\n<code>Fatal Error: Backup error</code></p>\n<p>The trace logs shows no signs of HTTP requests sent, except this snippet:</p>\n<details>\n<summary>\nSummary</summary>\n<p>{<br>\n\u201cSeverity\u201d: \u201c10\u201d,<br>\n\u201cTime\u201d: \u201c1603289138.352557\u201d,<br>\n\u201cType\u201d: \u201cAsyncFileOpened\u201d,<br>\n\u201cID\u201d: \u201c0000000000000000\u201d,<br>\n\u201cSuppressedEventCount\u201d: \u201c0\u201d,<br>\n\u201cFilename\u201d: \u201c/var/backup-credentials/azure_blobstore_credentials_for_minio\u201d,<br>\n\u201cFd\u201d: \u201c14\u201d,<br>\n\u201cFlags\u201d: \u201c2228225\u201d,<br>\n\u201cMachine\u201d: \u201c10.244.158.11:22323\u201d,<br>\n\u201cLogGroup\u201d: \u201cdefault\u201d<br>\n}<br>\n{<br>\n\u201cSeverity\u201d: \u201c40\u201d,<br>\n\u201cTime\u201d: \u201c1603289138.352762\u201d,<br>\n\u201cType\u201d: \u201cSystemError\u201d,<br>\n\u201cID\u201d: \u201c0000000000000000\u201d,<br>\n\u201cError\u201d: \u201cunknown_error\u201d,<br>\n\u201cErrorDescription\u201d: \u201cAn unknown error occurred\u201d,<br>\n\u201cErrorCode\u201d: \u201c4000\u201d,<br>\n\u201cBacktrace\u201d: \u201caddr2line -e fdbbackup.debug -p -C -f -i 0xaa654c 0xaa5e68 0xaa5f31 0xa69453 0x42fe8a 0x5d0808 0x5cefc8 0x5d0a8c 0x4f7c48 0x5d56bd 0x5d585c 0x4f7c48 0x5e3729 0x5d66c8 0x5d681d 0x9bf218 0x4f7bb0 0xaeac50 0x83c8b2 0x4b1469 0x7fb91832ab97\u201d,<br>\n\u201cMachine\u201d: \u201c10.244.158.11:22323\u201d,<br>\n\u201cLogGroup\u201d: \u201cdefault\u201d<br>\n}<br>\n{<br>\n\u201cSeverity\u201d: \u201c20\u201d,<br>\n\u201cTime\u201d: \u201c1603289138.352762\u201d,<br>\n\u201cType\u201d: \u201cBlobStoreEndpointRequestFailedRetryable\u201d,<br>\n\u201cID\u201d: \u201c0000000000000000\u201d,<br>\n\u201cError\u201d: \u201cunknown_error\u201d,<br>\n\u201cErrorDescription\u201d: \u201cAn unknown error occurred\u201d,<br>\n\u201cErrorCode\u201d: \u201c4000\u201d,<br>\n\u201cSuppressedEventCount\u201d: \u201c0\u201d,<br>\n\u201cConnectionEstablished\u201d: \u201c1\u201d,<br>\n\u201cRemoteHost\u201d: \u201cminio-gateway-service\u201d,<br>\n\u201cVerb\u201d: \u201cHEAD\u201d,<br>\n\u201cResource\u201d: \u201c/testbucket\u201d,<br>\n\u201cThisTry\u201d: \u201c1\u201d,<br>\n\u201cRetryDelay\u201d: \u201c2\u201d,<br>\n\u201cMachine\u201d: \u201c10.244.158.11:22323\u201d,<br>\n\u201cLogGroup\u201d: \u201cdefault\u201d<br>\n}<br>\n{<br>\n\u201cSeverity\u201d: \u201c10\u201d,<br>\n\u201cTime\u201d: \u201c1603289138.352762\u201d,<br>\n\u201cType\u201d: \u201cAsyncFileClosed\u201d,<br>\n\u201cID\u201d: \u201c0000000000000000\u201d,<br>\n\u201cSuppressedEventCount\u201d: \u201c0\u201d,<br>\n\u201cFd\u201d: \u201c14\u201d,<br>\n\u201cMachine\u201d: \u201c10.244.158.11:22323\u201d,<br>\n\u201cLogGroup\u201d: \u201cdefault\u201d<br>\n}</p>\n</details>\n<p>Setup:</p>\n<p>Kubernetes cluster in Azure<br>\nminIO service minio/minio:RELEASE.2020-10-18T21-54-12Z acting as a gateway to azure blobstore.<br>\nfbd-kubernetes-operator 0.18.0<br>\nfoundationdb-cluster 6.2.20<br>\nFoundationDBBackup object 6.2.20</p>\n<p>Logs from the kubernetes operator:</p>\n<details>\n<summary>\nSummary</summary>\n<p>2020-10-21T10:46:39.203Z INFO controller Running command {\u201cnamespace\u201d: \u201ctimeseries\u201d, \u201ccluster\u201d: \u201cfoundationdb-cluster\u201d, \u201cpath\u201d: \u201c/usr/bin/fdb/6.2/fdbbackup\u201d, \u201cargs\u201d: [\"/usr/bin/fdb/6.2/fdbbackup\", \u201cstatus\u201d, \u201c\u2013json\u201d, \u201c-C\u201d, \u201c/tmp/600276910\u201d, \u201c\u2013log\u201d, \u201c\u2013logdir\u201d, \u201c/var/log/fdb\u201d]}</p>\n<p>2020-10-21T10:46:39.482Z INFO controller Command completed {\u201cnamespace\u201d: \u201ctimeseries\u201d, \u201ccluster\u201d: \u201cfoundationdb-cluster\u201d, \u201coutput\u201d: \"{\u201cSchemaVersion\u201d:\u201c1\u2026\u201d}</p>\n<p>2020-10-21T10:46:39.483Z INFO controller Running command {\u201cnamespace\u201d: \u201ctimeseries\u201d, \u201ccluster\u201d: \u201cfoundationdb-cluster\u201d, \u201cpath\u201d: \u201c/usr/bin/fdb/6.2/fdbbackup\u201d, \u201cargs\u201d: [\"/usr/bin/fdb/6.2/fdbbackup\", \u201cstart\u201d, \u201c-d\u201d, \u201cblobstore://timelordsfdbtest@minio-gateway-service:9000/fdb-backup?bucket=fdb-backups&amp;sc=0\u201d, \u201c-s\u201d, \u201c60\u201d, \u201c-z\u201d, \u201c-C\u201d, \u201c/tmp/249282357\u201d, \u201c\u2013log\u201d, \u201c\u2013logdir\u201d, \u201c/var/log/fdb\u201d]}</p>\n<p>2020-10-21T10:46:49.554Z ERROR controller Error from FDB command {\u201cnamespace\u201d: \u201ctimeseries\u201d, \u201ccluster\u201d: \u201cfoundationdb-cluster\u201d, \u201ccode\u201d: -1, \u201cstdout\u201d: \u201c\u201d, \u201cstderr\u201d: \u201c\u201d, \u201cerror\u201d: \u201csignal: killed\u201d}</p>\n<p>2020-10-21T10:46:49.554Z INFO controller Reconciliation terminated early {\u201cnamespace\u201d: \u201ctimeseries\u201d, \u201cbackup\u201d: \u201cfoundationdb-cluster\u201d, \u201clastAction\u201d: \u201ccontrollers.StartBackup\u201d}</p>\n<p>2020-10-21T10:46:49.554Z ERROR controller Error in reconciliation {\u201csubReconciler\u201d: \u201ccontrollers.StartBackup\u201d, \u201cnamespace\u201d: \u201ctimeseries\u201d, \u201cbackup\u201d: \u201cfoundationdb-cluster\u201d, \u201cerror\u201d: \u201csignal: killed\u201d}</p>\n<p><a href=\"http://github.com/go-logr/zapr.(*zapLogger\" rel=\"noopener nofollow ugc\">github.com/go-logr/zapr.(*zapLogger</a>).Error</p>\n<p>/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128</p>\n<p><a href=\"http://github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*CliAdminClient\" rel=\"noopener nofollow ugc\">github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*CliAdminClient</a>).runCommand</p>\n<p>/workspace/controllers/admin_client.go:255</p>\n<p><a href=\"http://github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*CliAdminClient\" rel=\"noopener nofollow ugc\">github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*CliAdminClient</a>).StartBackup</p>\n<p>/workspace/controllers/admin_client.go:509</p>\n<p><a href=\"http://github.com/FoundationDB/fdb-kubernetes-operator/controllers.StartBackup.Reconcile\" rel=\"noopener nofollow ugc\">github.com/FoundationDB/fdb-kubernetes-operator/controllers.StartBackup.Reconcile</a></p>\n<p>/workspace/controllers/start_backup.go:46</p>\n<p><a href=\"http://github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBBackupReconciler\" rel=\"noopener nofollow ugc\">github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBBackupReconciler</a>).Reconcile</p>\n<p>/workspace/controllers/backup_controller.go:82</p>\n<p><a href=\"http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller\" rel=\"noopener nofollow ugc\">sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller</a>).reconcileHandler</p>\n<p>/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256</p>\n<p><a href=\"http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller\" rel=\"noopener nofollow ugc\">sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller</a>).processNextWorkItem</p>\n<p>/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232</p>\n<p><a href=\"http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller\" rel=\"noopener nofollow ugc\">sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller</a>).worker</p>\n<p>/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211</p>\n<p><a href=\"http://k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\" rel=\"noopener nofollow ugc\">k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1</a></p>\n<p>/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152</p>\n<p><a href=\"http://k8s.io/apimachinery/pkg/util/wait.JitterUntil\" rel=\"noopener nofollow ugc\">k8s.io/apimachinery/pkg/util/wait.JitterUntil</a></p>\n<p>/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153</p>\n<p><a href=\"http://k8s.io/apimachinery/pkg/util/wait.Until\" rel=\"noopener nofollow ugc\">k8s.io/apimachinery/pkg/util/wait.Until</a></p>\n<p>/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88</p>\n</details>\n<p>The backup pods connects to the foundationdb cluster (<code>fdbcli --exec status</code> on the backup agent pods show they\u2019re healthy)</p>\n<p>When I try to connect to minIO using aws client (installed manually on the backup agents)</p>\n<p><code>aws --endpoint-url http://minio-gateway-service:9000 s3 ls</code></p>\n<p>This command gives me the buckets in azure blobstore, and shows that the minIO azure gateway is s3 compatible. It also shows that minio-gateway-service:9000 is reachable from the pod. Note: it is not configured using SSL.</p>\n<p>Furthermore, the file <code>/var/backup-credentials/azure_blobstore_credentials_for_minio</code> file contains</p>\n<details>\n<summary>\nSummary</summary>\n<pre><code>{\n  \"accounts\" : {\n    \"timelordsfdbtest@minio-gateway-service\" :   { \"secret\" : \"7KeyHasBeenReplacedByThisSentenceA==\" }\n  }\n}\n</code></pre>\n</details>\n<p>Any ideas on what could be wrong, or other things I could try out, would be highly appreciated!</p>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-22T08:10:38.670Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 125,
        "reads": 50,
        "readers_count": 49,
        "score": 650.0,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Matias Holte",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "http://k8s.io/apimachinery/pkg/util/wait.Until",
            "internal": false,
            "reflection": false,
            "clicks": 0
          },
          {
            "url": "http://github.com/go-logr/zapr.(*zapLogger",
            "internal": false,
            "reflection": false,
            "clicks": 0
          },
          {
            "url": "http://github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBBackupReconciler",
            "internal": false,
            "reflection": false,
            "clicks": 0
          },
          {
            "url": "http://github.com/FoundationDB/fdb-kubernetes-operator/controllers.StartBackup.Reconcile",
            "internal": false,
            "reflection": false,
            "clicks": 0
          },
          {
            "url": "http://github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*CliAdminClient",
            "internal": false,
            "reflection": false,
            "clicks": 0
          },
          {
            "url": "http://k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1",
            "internal": false,
            "reflection": false,
            "clicks": 0
          },
          {
            "url": "http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller",
            "internal": false,
            "reflection": false,
            "clicks": 0
          },
          {
            "url": "http://k8s.io/apimachinery/pkg/util/wait.JitterUntil",
            "internal": false,
            "reflection": false,
            "clicks": 0
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 1
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 746,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 8137,
        "name": "Petr Tich\u00fd",
        "username": "petr-tichy",
        "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png",
        "created_at": "2020-10-22T13:28:56.294Z",
        "cooked": "<p>The problem here is due to FDB choking when the length of secret key is &gt; 64 characters. I have compiled a custom version of minio with hardcoded Azure Blob credentials, and configuring something short for FDB &lt;-&gt; minio authentication works.</p>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-22T13:28:56.294Z",
        "reply_count": 2,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 41,
        "readers_count": 40,
        "score": 78.2,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Petr Tich\u00fd",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 3
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 837,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8138,
        "name": "Matias Holte",
        "username": "matiasholte",
        "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png",
        "created_at": "2020-10-22T13:32:00.310Z",
        "cooked": "<p>Thanks, Petr, you saved me from lots of wasteful trial and failures!<br>\nDo you know if this is (going to be) fixed in any specific FDB version?</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-22T13:32:00.310Z",
        "reply_count": 0,
        "reply_to_post_number": 2,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 39,
        "readers_count": 38,
        "score": 12.8,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Matias Holte",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 837,
          "username": "petr-tichy",
          "name": "Petr Tich\u00fd",
          "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 746,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8174,
        "name": "Alex Miller",
        "username": "alexmiller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "created_at": "2020-10-22T23:12:24.222Z",
        "cooked": "<p>Is there an issue for this?  I don\u2019t recall hearing about this bug before\u2026</p>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-22T23:12:24.222Z",
        "reply_count": 0,
        "reply_to_post_number": 2,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 37,
        "readers_count": 36,
        "score": 7.4,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Alex Miller",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 837,
          "username": "petr-tichy",
          "name": "Petr Tich\u00fd",
          "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 13,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8175,
        "name": "Matias Holte",
        "username": "matiasholte",
        "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png",
        "created_at": "2020-10-23T09:28:08.790Z",
        "cooked": "<p>I can confirm that a shorter secret key indeed fixed the issue, and I can now see backup files in azure blobstore <img src=\"https://emoji.discourse-cdn.com/twitter/slight_smile.png?v=9\" title=\":slight_smile:\" class=\"emoji\" alt=\":slight_smile:\"><br>\n(Have yet to verify the integrity of the backup, but at least it\u2019s a step forward)</p>\n<p>I used the same approach as you Petr-tichy, changed a few lines in minio to use an azure api key from environment variable, instead of supplied by the user.<br>\nWould be nice to have it fixed in foundationdb though, but you saved the day Petr-tichy <img src=\"https://emoji.discourse-cdn.com/twitter/slight_smile.png?v=9\" title=\":slight_smile:\" class=\"emoji\" alt=\":slight_smile:\"></p>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-23T09:28:31.004Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 37,
        "readers_count": 36,
        "score": 17.4,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Matias Holte",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 746,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8177,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-10-23T19:25:41.644Z",
        "cooked": "<p>I found the problem.  In FDB\u2019s blob client, the <code>hmac_sha1()</code> method handles the case where the key is shorter than the 64 byte block size but doesn\u2019t handle the case where it is longer as per</p>\n<aside class=\"onebox wikipedia\">\n  <header class=\"source\">\n      <a href=\"https://en.wikipedia.org/wiki/HMAC#Implementation\" target=\"_blank\" rel=\"noopener\">en.wikipedia.org</a>\n  </header>\n  <article class=\"onebox-body\">\n    <div class=\"aspect-image\" style=\"--aspect-ratio:220/165;\"><img src=\"https://global.discourse-cdn.com/foundationdb/original/1X/8c7af1a2be1cefb10aa18cee4992de07da2a7b9b.png\" class=\"thumbnail\" width=\"220\" height=\"165\"></div>\n\n<h3><a href=\"https://en.wikipedia.org/wiki/HMAC#Implementation\" target=\"_blank\" rel=\"noopener\">HMAC | Implementation</a></h3>\n\n<p>The following pseudocode demonstrates how HMAC may be implemented. Blocksize is 64 (bytes) when using one of the following hash functions: SHA-1, MD5, RIPEMD-128/160.\n</p>\n\n  </article>\n  <div class=\"onebox-metadata\">\n    \n    \n  </div>\n  <div style=\"clear: both\"></div>\n</aside>\n\n<p>I\u2019ll fix this soon.</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-23T19:25:41.644Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 35,
        "readers_count": 34,
        "score": 7.0,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://en.wikipedia.org/wiki/HMAC#Implementation",
            "internal": false,
            "reflection": false,
            "title": "HMAC - Wikipedia",
            "clicks": 3
          }
        ],
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8181,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-10-26T04:19:20.958Z",
        "cooked": "<p><a class=\"mention\" href=\"/u/petr-tichy\">@petr-tichy</a> <a class=\"mention\" href=\"/u/matiasholte\">@matiasholte</a> I have a PR against release-6.2 with this fix, could either of you verify that it works?</p>\n<aside class=\"onebox githubpullrequest\">\n  <header class=\"source\">\n      <a href=\"https://github.com/apple/foundationdb/pull/3964\" target=\"_blank\" rel=\"noopener\">github.com/apple/foundationdb</a>\n  </header>\n  <article class=\"onebox-body\">\n    <div class=\"github-row\">\n  <div class=\"github-icon-container\" title=\"Pull Request\">\n    <svg width=\"60\" height=\"60\" class=\"github-icon\" viewBox=\"0 0 12 16\" aria-hidden=\"true\"><path d=\"M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0 0 10 15a1.993 1.993 0 0 0 1-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 0 0-1 3.72v6.56A1.993 1.993 0 0 0 2 15a1.993 1.993 0 0 0 1-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z\"></path></svg>\n  </div>\n\n  <div class=\"github-info-container\">\n    <h4>\n      <a href=\"https://github.com/apple/foundationdb/pull/3964\" target=\"_blank\" rel=\"noopener\">Bug fix, blob client was not correctly using keys longer than 64 byte\u2026</a>\n    </h4>\n\n    <div class=\"branches\">\n      <code>apple:release-6.2</code> \u2190 <code>satherton:fix-blob-key-length</code>\n    </div>\n\n    <div class=\"github-info\">\n      <div class=\"date\">\n        opened <span class=\"discourse-local-date\" data-format=\"ll\" data-date=\"2020-10-26\" data-time=\"04:16:13\" data-timezone=\"UTC\">04:16AM - 26 Oct 20 UTC</span>\n      </div>\n\n      <div class=\"user\">\n        <a href=\"https://github.com/satherton\" target=\"_blank\" rel=\"noopener\">\n          <img alt=\"satherton\" src=\"https://global.discourse-cdn.com/foundationdb/original/1X/dcab1adc161b25c2cd76455166702f4cdf35a09e.png\" class=\"onebox-avatar-inline\" width=\"20\" height=\"20\">\n          satherton\n        </a>\n      </div>\n\n      <div class=\"lines\" title=\"1 commits changed 1 files with 6 additions and 1 deletions\">\n        <a href=\"https://github.com/apple/foundationdb/pull/3964/files\" target=\"_blank\" rel=\"noopener\">\n          <span class=\"added\">+6</span>\n          <span class=\"removed\">-1</span>\n        </a>\n      </div>\n    </div>\n\n  </div>\n</div>\n\n  </article>\n  <div class=\"onebox-metadata\">\n    \n    \n  </div>\n  <div style=\"clear: both\"></div>\n</aside>\n\n<p>Also <a class=\"mention\" href=\"/u/petr-tichy\">@petr-tichy</a> thanks so much for figuring out what the issue was.</p>",
        "post_number": 7,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-26T04:19:20.958Z",
        "reply_count": 2,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 34,
        "readers_count": 33,
        "score": 26.8,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/pull/3964",
            "internal": false,
            "reflection": false,
            "title": "Bug fix, blob client was not correctly using keys longer than 64 byte\u2026 by satherton \u00b7 Pull Request #3964 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 7
          },
          {
            "url": "https://github.com/satherton",
            "internal": false,
            "reflection": false,
            "title": "satherton (Steve Atherton) \u00b7 GitHub",
            "clicks": 0
          },
          {
            "url": "https://github.com/apple/foundationdb/pull/3964/files",
            "internal": false,
            "reflection": false,
            "title": "Bug fix, blob client was not correctly using keys longer than 64 byte\u2026 by satherton \u00b7 Pull Request #3964 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 0
          }
        ],
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/7",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8718,
        "name": "Matias Holte",
        "username": "matiasholte",
        "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png",
        "created_at": "2020-10-26T11:37:12.913Z",
        "cooked": "<p>I get errors when I compile foundationdb locally (not related to your fix), so I cannot test it until I have an image to download.<br>\nShouldn\u2019t be too hard to test, using minio with a long password?</p>",
        "post_number": 8,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-26T11:37:12.913Z",
        "reply_count": 1,
        "reply_to_post_number": 7,
        "quote_count": 0,
        "incoming_link_count": 14,
        "reads": 33,
        "readers_count": 32,
        "score": 81.6,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Matias Holte",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 7,
          "username": "SteavedHams",
          "name": "Steve Atherton",
          "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 746,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/8",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8720,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-10-26T16:08:39.257Z",
        "cooked": "<p>No problem, yes I\u2019ll test with minio today.</p>",
        "post_number": 9,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-26T16:08:39.257Z",
        "reply_count": 0,
        "reply_to_post_number": 8,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 33,
        "readers_count": 32,
        "score": 6.6,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "reply_to_user": {
          "id": 746,
          "username": "matiasholte",
          "name": "Matias Holte",
          "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/9",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8723,
        "name": "Petr Tich\u00fd",
        "username": "petr-tichy",
        "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png",
        "created_at": "2020-10-26T20:18:32.099Z",
        "cooked": "<p>Yes, I can confirm this fixes the issue with authentication, but there is yet something else incompatible that I\u2019m looking into. I suspect something with the partial file retrieval\u2026</p>",
        "post_number": 10,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-26T20:19:18.596Z",
        "reply_count": 1,
        "reply_to_post_number": 7,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 33,
        "readers_count": 32,
        "score": 81.6,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Petr Tich\u00fd",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 7,
          "username": "SteavedHams",
          "name": "Steve Atherton",
          "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png"
        },
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 2
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 837,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/10",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8724,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-10-26T22:36:47.961Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"petr-tichy\" data-post=\"10\" data-topic=\"2404\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/petr-tichy/48/1427_2.png\" class=\"avatar\"> petr-tichy:</div>\n<blockquote>\n<p>I suspect something with the partial file retrieval\u2026</p>\n</blockquote>\n</aside>\n<p><code>--knob_http_verbose_level=3</code> will dump full requests/responses to stdout.  2 will omit response content.  I think the response content bytes are printed directly, no escaping.</p>",
        "post_number": 11,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-26T22:36:47.961Z",
        "reply_count": 1,
        "reply_to_post_number": 10,
        "quote_count": 1,
        "incoming_link_count": 0,
        "reads": 33,
        "readers_count": 32,
        "score": 11.6,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/11",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8727,
        "name": "Petr Tich\u00fd",
        "username": "petr-tichy",
        "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png",
        "created_at": "2020-10-27T21:37:44.478Z",
        "cooked": "<p>Yes, that was it. And thanks <a class=\"mention\" href=\"/u/steavedhams\">@SteavedHams</a> for the tip. The <a href=\"https://min.io/\" rel=\"noopener nofollow ugc\">MinIO</a> possibly inadvertenly forwards the <code>Content-MD5</code> header back to FDB, but does that also for requests with the <code>Range</code> header, where the response body is just the requested file part, but the <code>Content-MD5</code> is for the whole file. So all requests for files bigger than <code>read_block_size</code> would fail the check.<br>\nThere is a simple workaround to set the <code>rbs</code> backup URL parameter to something high (2^30 worked for me). This allowed me to restore 5 TB from Azure Blob Storage.</p>\n<p>I scanned the <a href=\"https://docs.aws.amazon.com/AmazonS3/latest/API/s3-api.pdf\" rel=\"noopener nofollow ugc\">AWS S3 specs</a> but found no mention of the <code>Content-MD5</code> on <em>responses</em>. It looks like AWS S3 never uses it. (although it is used by the client in <em>requests</em>). So I suspect that this is the fix: <a href=\"https://github.com/apple/foundationdb/pull/3978\" rel=\"noopener nofollow ugc\">https://github.com/apple/foundationdb/pull/3978</a></p>",
        "post_number": 12,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-27T21:37:44.478Z",
        "reply_count": 1,
        "reply_to_post_number": 11,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 30,
        "readers_count": 29,
        "score": 16.0,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Petr Tich\u00fd",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/pull/3978",
            "internal": false,
            "reflection": false,
            "title": "Remove the check of Content-MD5 on responses by petr-tichy \u00b7 Pull Request #3978 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 8
          },
          {
            "url": "https://min.io/",
            "internal": false,
            "reflection": false,
            "title": "MinIO | High Performance, Kubernetes Native Object Storage",
            "clicks": 1
          },
          {
            "url": "https://docs.aws.amazon.com/AmazonS3/latest/API/s3-api.pdf",
            "internal": false,
            "reflection": false,
            "clicks": 1
          }
        ],
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 7,
          "username": "SteavedHams",
          "name": "Steve Atherton",
          "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 837,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/12",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 8729,
        "name": "Steve Atherton",
        "username": "SteavedHams",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "created_at": "2020-10-28T08:23:29.260Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"petr-tichy\" data-post=\"12\" data-topic=\"2404\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/petr-tichy/48/1427_2.png\" class=\"avatar\"> petr-tichy:</div>\n<blockquote>\n<p>There is a simple workaround to set the <code>rbs</code> backup URL parameter to something high (2^30 worked for me)</p>\n</blockquote>\n</aside>\n<p>To be clear, this workaround actually means that every read of any block of a backup file by an FDB restore job will actually read <em>the entire file</em> and then just extract the part it is interested in and discard the rest.  In the current restore process, backup files are read in parallel as each 1MB block of a backup file is independently decodable and processed in a random order to enable greater restore parallelism and workload balancing across database shards.</p>",
        "post_number": 13,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2020-10-28T08:23:29.260Z",
        "reply_count": 1,
        "reply_to_post_number": 12,
        "quote_count": 1,
        "incoming_link_count": 3,
        "reads": 29,
        "readers_count": 28,
        "score": 25.8,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Steve Atherton",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": "",
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 7,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/13",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 9094,
        "name": "Petr Tich\u00fd",
        "username": "petr-tichy",
        "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png",
        "created_at": "2021-02-24T21:37:08.068Z",
        "cooked": "<p>Thanks for the great hints. I was able to identify the exact cause of the invalid <code>Content-MD5</code> header on certain requests proxied thru MinIO to Azure Blob storage. The issue was basically MinIO did a first separate request to get the object metadata, including <code>Content-MD5</code> , and served that even to the partial requests, which made these invalid to clients actually checking it (like FDB). This has recently fixed in <a href=\"https://github.com/minio/minio/releases/tag/RELEASE.2021-02-24T18-44-45Z\" class=\"inline-onebox\" rel=\"noopener nofollow ugc\">Release Minor Bugfix Release \u00b7 minio/minio \u00b7 GitHub</a>. Thus MinIO is currently fully usable as Azure Blob storage gateway to FDB backup.</p>",
        "post_number": 14,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2021-02-24T21:37:08.068Z",
        "reply_count": 1,
        "reply_to_post_number": 13,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 28,
        "readers_count": 27,
        "score": 50.6,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Petr Tich\u00fd",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/minio/minio/releases/tag/RELEASE.2021-02-24T18-44-45Z",
            "internal": false,
            "reflection": false,
            "title": "Release Minor Bugfix Release \u00b7 minio/minio \u00b7 GitHub",
            "clicks": 3
          }
        ],
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 7,
          "username": "SteavedHams",
          "name": "Steve Atherton",
          "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png"
        },
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 2
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 837,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/14",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 11351,
        "name": "Hari B",
        "username": "harikb",
        "avatar_template": "/user_avatar/forums.foundationdb.org/harikb/{size}/1033_2.png",
        "created_at": "2022-06-27T18:32:25.783Z",
        "cooked": "<p>Listing this ticket here for anyone looking at this</p><aside class=\"onebox githubpullrequest\" data-onebox-src=\"https://github.com/minio/minio/pull/14418\">\n  <header class=\"source\">\n\n      <a href=\"https://github.com/minio/minio/pull/14418\" target=\"_blank\" rel=\"noopener nofollow ugc\">github.com/minio/minio</a>\n  </header>\n\n  <article class=\"onebox-body\">\n    <div class=\"github-row\">\n  <div class=\"github-icon-container\" title=\"Pull Request\">\n    <svg width=\"60\" height=\"60\" class=\"github-icon\" viewbox=\"0 0 12 16\" aria-hidden=\"true\"><path d=\"M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0 0 10 15a1.993 1.993 0 0 0 1-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 0 0-1 3.72v6.56A1.993 1.993 0 0 0 2 15a1.993 1.993 0 0 0 1-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z\"></path></svg>\n  </div>\n\n  <div class=\"github-info-container\">\n    <h4>\n      <a href=\"https://github.com/minio/minio/pull/14418\" target=\"_blank\" rel=\"noopener nofollow ugc\">Removing Azure, GCS, HDFS gateway implementations</a>\n    </h4>\n\n    <div class=\"branches\">\n      <code>minio:deprecation-gateway</code> \u2190 <code>harshavardhana:remove-gateway</code>\n    </div>\n\n    <div class=\"github-info\">\n      <div class=\"date\">\n        opened <span class=\"discourse-local-date\" data-format=\"ll\" data-date=\"2022-02-27\" data-time=\"04:46:43\" data-timezone=\"UTC\">04:46AM - 27 Feb 22 UTC</span>\n      </div>\n\n      <div class=\"user\">\n        <a href=\"https://github.com/harshavardhana\" target=\"_blank\" rel=\"noopener nofollow ugc\">\n          <img alt=\"harshavardhana\" src=\"https://global.discourse-cdn.com/foundationdb/original/2X/9/93367a1e34469db3635269300a7d26b509900b7e.jpeg\" class=\"onebox-avatar-inline\" width=\"20\" height=\"20\">\n          harshavardhana\n        </a>\n      </div>\n\n      <div class=\"lines\" title=\"1 commits changed 18 files with 6 additions and 5041 deletions\">\n        <a href=\"https://github.com/minio/minio/pull/14418/files\" target=\"_blank\" rel=\"noopener nofollow ugc\">\n          <span class=\"added\">+6</span>\n          <span class=\"removed\">-5041</span>\n        </a>\n      </div>\n    </div>\n  </div>\n</div>\n\n  <div class=\"github-row\">\n    <p class=\"github-body-container\">## Description\nRemoving Azure, GCS, HDFS gateway implementations\n\n## Motivati<span class=\"show-more-container\"><a href=\"https://github.com/minio/minio/pull/14418\" target=\"_blank\" rel=\"noopener nofollow ugc\" class=\"show-more\">\u2026</a></span><span class=\"excerpt hidden\">on and Context\nrefer #14331\n\n## How to test this PR?\nNothing spectacular to test. \n\n## Types of changes\n- [ ] Bug fix (non-breaking change which fixes an issue)\n- [ ] New feature (non-breaking change which adds functionality)\n- [ ] Optimization (provides speedup with no functional changes)\n- [x] Breaking change (fix or feature that would cause existing functionality to change)\n\n## Checklist:\n- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)\n- [x] Documentation updated\n- [ ] Unit tests added/updated</span></p>\n  </div>\n\n  </article>\n\n  <div class=\"onebox-metadata\">\n    \n    \n  </div>\n\n  <div style=\"clear: both\"></div>\n</aside>\n",
        "post_number": 15,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2022-06-27T18:32:25.783Z",
        "reply_count": 0,
        "reply_to_post_number": 14,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 17,
        "readers_count": 16,
        "score": 13.4,
        "yours": false,
        "topic_id": 2404,
        "topic_slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
        "display_username": "Hari B",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/minio/minio/pull/14418",
            "internal": false,
            "reflection": false,
            "title": "Removing Azure, GCS, HDFS gateway implementations by harshavardhana \u00b7 Pull Request #14418 \u00b7 minio/minio \u00b7 GitHub",
            "clicks": 5
          }
        ],
        "read": true,
        "user_title": "",
        "reply_to_user": {
          "id": 837,
          "username": "petr-tichy",
          "name": "Petr Tich\u00fd",
          "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 405,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/foundatiodbbackup-against-azure-blobstore-unknown-error/2404/15",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      8135,
      8137,
      8138,
      8174,
      8175,
      8177,
      8181,
      8718,
      8720,
      8723,
      8724,
      8727,
      8729,
      9094,
      11351
    ]
  },
  "timeline_lookup": [
    [
      1,
      1826
    ],
    [
      2,
      1825
    ],
    [
      6,
      1824
    ],
    [
      7,
      1822
    ],
    [
      8,
      1821
    ],
    [
      12,
      1820
    ],
    [
      14,
      1700
    ],
    [
      15,
      1212
    ]
  ],
  "suggested_topics": [],
  "tags": [],
  "tags_descriptions": {},
  "fancy_title": "FoundatioDBBackup against azure blobstore - unknown error",
  "id": 2404,
  "title": "FoundatioDBBackup against azure blobstore - unknown error",
  "posts_count": 15,
  "created_at": "2020-10-22T08:10:38.576Z",
  "views": 1476,
  "reply_count": 10,
  "like_count": 8,
  "last_posted_at": "2022-06-27T18:32:25.783Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "foundatiodbbackup-against-azure-blobstore-unknown-error",
  "category_id": 16,
  "word_count": 1558,
  "deleted_at": null,
  "user_id": 746,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": null,
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_2404",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 15,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 5,
  "show_read_indicator": false,
  "thumbnails": null,
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "FoundationDb fdbbackup to Azure Blob Store",
      "id": 3392,
      "title": "FoundationDb fdbbackup to Azure Blob Store",
      "slug": "foundationdb-fdbbackup-to-azure-blob-store",
      "posts_count": 8,
      "reply_count": 5,
      "highest_post_number": 8,
      "image_url": null,
      "created_at": "2022-06-21T22:18:36.564Z",
      "last_posted_at": "2022-11-10T10:12:28.003Z",
      "bumped": true,
      "bumped_at": "2022-11-10T10:12:28.003Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 713,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 915,
            "username": "skr1942",
            "name": "srai",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/s/9f8e36/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 849,
            "username": "johscheuer",
            "name": "Johannes Scheuermann",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/j/f475e1/{size}.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 405,
            "username": "harikb",
            "name": "Hari B",
            "avatar_template": "/user_avatar/forums.foundationdb.org/harikb/{size}/1033_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 1128,
            "username": "manfontan",
            "name": "Manuel Fontan",
            "avatar_template": "/user_avatar/forums.foundationdb.org/manfontan/{size}/1370_2.png",
            "trust_level": 2
          }
        }
      ]
    },
    {
      "fancy_title": "FDB Backup, minio, and minio gateway (paid service)",
      "id": 2898,
      "title": "FDB Backup, minio, and minio gateway (paid service)",
      "slug": "fdb-backup-minio-and-minio-gateway-paid-service",
      "posts_count": 1,
      "reply_count": 0,
      "highest_post_number": 1,
      "image_url": null,
      "created_at": "2021-09-20T18:14:03.477Z",
      "last_posted_at": "2021-09-20T18:14:03.533Z",
      "bumped": true,
      "bumped_at": "2021-09-20T18:14:03.533Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 617,
      "category_id": 17,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest single",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 405,
            "username": "harikb",
            "name": "Hari B",
            "avatar_template": "/user_avatar/forums.foundationdb.org/harikb/{size}/1033_2.png",
            "trust_level": 2
          }
        }
      ]
    },
    {
      "fancy_title": "Fdbbackup to blobstore failed using blob_credentials",
      "id": 2794,
      "title": "Fdbbackup to blobstore failed using blob_credentials",
      "slug": "fdbbackup-to-blobstore-failed-using-blob-credentials",
      "posts_count": 1,
      "reply_count": 0,
      "highest_post_number": 1,
      "image_url": null,
      "created_at": "2021-07-16T02:42:49.849Z",
      "last_posted_at": "2021-07-16T02:42:49.932Z",
      "bumped": true,
      "bumped_at": "2021-07-16T06:52:52.308Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 481,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest single",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 965,
            "username": "boorishwreck",
            "name": "",
            "avatar_template": "/user_avatar/forums.foundationdb.org/boorishwreck/{size}/1135_2.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Sanity check: FoundationDB backup blobstore credentials permissions errors",
      "id": 1944,
      "title": "Sanity check: FoundationDB backup blobstore credentials permissions errors",
      "slug": "sanity-check-foundationdb-backup-blobstore-credentials-permissions-errors",
      "posts_count": 20,
      "reply_count": 4,
      "highest_post_number": 20,
      "image_url": null,
      "created_at": "2020-02-13T17:22:53.536Z",
      "last_posted_at": "2020-02-19T00:40:20.641Z",
      "bumped": true,
      "bumped_at": "2020-02-19T00:40:20.641Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 1493,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 484,
            "username": "ksnavely",
            "name": "Kyle Snavely",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ksnavely/{size}/483_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 7,
            "username": "SteavedHams",
            "name": "Steve Atherton",
            "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "FoundationDB fdbbackup",
      "id": 1460,
      "title": "FoundationDB fdbbackup",
      "slug": "foundationdb-fdbbackup",
      "posts_count": 7,
      "reply_count": 2,
      "highest_post_number": 7,
      "image_url": null,
      "created_at": "2019-06-17T18:54:47.516Z",
      "last_posted_at": "2019-10-09T03:07:15.974Z",
      "bumped": true,
      "bumped_at": "2019-10-09T03:07:15.974Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 2461,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 579,
            "username": "approachcp",
            "name": "",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/f04885/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 581,
            "username": "surprisetalk",
            "name": "Taylor Sarrafian",
            "avatar_template": "/user_avatar/forums.foundationdb.org/surprisetalk/{size}/579_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 7,
            "username": "SteavedHams",
            "name": "Steve Atherton",
            "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
            "trust_level": 4
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 7,
        "username": "SteavedHams",
        "name": "Steve Atherton",
        "avatar_template": "/user_avatar/forums.foundationdb.org/steavedhams/{size}/18_2.png",
        "post_count": 5,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 4
      },
      {
        "id": 746,
        "username": "matiasholte",
        "name": "Matias Holte",
        "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png",
        "post_count": 4,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 837,
        "username": "petr-tichy",
        "name": "Petr Tich\u00fd",
        "avatar_template": "/user_avatar/forums.foundationdb.org/petr-tichy/{size}/1427_2.png",
        "post_count": 4,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 13,
        "username": "alexmiller",
        "name": "Alex Miller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "post_count": 1,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 4
      },
      {
        "id": 405,
        "username": "harikb",
        "name": "Hari B",
        "avatar_template": "/user_avatar/forums.foundationdb.org/harikb/{size}/1033_2.png",
        "post_count": 1,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 2
      }
    ],
    "created_by": {
      "id": 746,
      "username": "matiasholte",
      "name": "Matias Holte",
      "avatar_template": "/user_avatar/forums.foundationdb.org/matiasholte/{size}/1124_2.png"
    },
    "last_poster": {
      "id": 405,
      "username": "harikb",
      "name": "Hari B",
      "avatar_template": "/user_avatar/forums.foundationdb.org/harikb/{size}/1033_2.png"
    },
    "links": [
      {
        "url": "https://github.com/apple/foundationdb/pull/3978",
        "title": "Remove the check of Content-MD5 on responses by petr-tichy \u00b7 Pull Request #3978 \u00b7 apple/foundationdb \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 8,
        "user_id": 837,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://github.com/apple/foundationdb/pull/3964",
        "title": "Bug fix, blob client was not correctly using keys longer than 64 byte\u2026 by satherton \u00b7 Pull Request #3964 \u00b7 apple/foundationdb \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 7,
        "user_id": 7,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://github.com/minio/minio/pull/14418",
        "title": "Removing Azure, GCS, HDFS gateway implementations by harshavardhana \u00b7 Pull Request #14418 \u00b7 minio/minio \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 5,
        "user_id": 405,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://en.wikipedia.org/wiki/HMAC#Implementation",
        "title": "HMAC - Wikipedia",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 3,
        "user_id": 7,
        "domain": "en.wikipedia.org",
        "root_domain": "wikipedia.org"
      },
      {
        "url": "https://github.com/minio/minio/releases/tag/RELEASE.2021-02-24T18-44-45Z",
        "title": "Release Minor Bugfix Release \u00b7 minio/minio \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 3,
        "user_id": 837,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://docs.aws.amazon.com/AmazonS3/latest/API/s3-api.pdf",
        "title": null,
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 1,
        "user_id": 837,
        "domain": "docs.aws.amazon.com",
        "root_domain": "amazon.com"
      },
      {
        "url": "https://min.io/",
        "title": "MinIO | High Performance, Kubernetes Native Object Storage",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 1,
        "user_id": 837,
        "domain": "min.io",
        "root_domain": "min.io"
      }
    ]
  },
  "bookmarks": []
}