{
  "post_stream": {
    "posts": [
      {
        "id": 11129,
        "name": "",
        "username": "Clindy",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/f04885/{size}.png",
        "created_at": "2022-05-17T08:55:43.396Z",
        "cooked": "<p>Hello,<br>\nMy cluster deployment was 3 DCs, 2 regions.The FDB database version is <code>6.3.23</code> .</p>\n<p>region.json</p>\n<blockquote>\n<p>{<br>\n\u201cregions\u201d: [ {<br>\n\u201cdatacenters\u201d:[{<br>\n\u201cid\u201d : \u201cdc1\u201d,<br>\n\u201cpriority\u201d: 1<br>\n},{<br>\n\u201cid\u201d: \u201cdc2\u201d,<br>\n\u201cpriority\u201d: 0,<br>\n\u201csatellite\u201d: 1,<br>\n\u201csatellite_logs\u201d: 2<br>\n}],<br>\n\u201csatellite_redundancy_mode\u201d: \u201cone_satellite_double\u201d<br>\n},{<br>\n\u201cdatacenters\u201d:[{<br>\n\u201cid\u201d: \u201cdc3\u201d,<br>\n\u201cpriority\u201d: 0<br>\n}]<br>\n}]<br>\n}<br>\n<code>DC1</code> is the primary DC. <code>DC2</code> is satellite DC, and <code>DC3</code> is the one in a different region.<br>\n<code>fdbcli --exec status</code><br>\n<div class=\"lightbox-wrapper\"><a class=\"lightbox\" href=\"https://global.discourse-cdn.com/foundationdb/original/2X/a/a4c7fc1d6114672c9792f82339ddf436e6d9a7bd.png\" data-download-href=\"/uploads/short-url/nvILMqd2kLBrE66QMDKdZhaEytL.png?dl=1\" title=\"multi-region\" rel=\"noopener nofollow ugc\"><img src=\"https://global.discourse-cdn.com/foundationdb/original/2X/a/a4c7fc1d6114672c9792f82339ddf436e6d9a7bd.png\" alt=\"multi-region\" data-base62-sha1=\"nvILMqd2kLBrE66QMDKdZhaEytL\" width=\"407\" height=\"500\" data-dominant-color=\"060606\"><div class=\"meta\"><svg class=\"fa d-icon d-icon-far-image svg-icon\" aria-hidden=\"true\"><use href=\"#far-image\"></use></svg><span class=\"filename\">multi-region</span><span class=\"informations\">637\u00d7781 18.6 KB</span><svg class=\"fa d-icon d-icon-discourse-expand svg-icon\" aria-hidden=\"true\"><use href=\"#discourse-expand\"></use></svg></div></a></div><br>\nI simulated <code>DC1</code> failure by stopping all processes deployed in primary datacenter <code>DC1</code>, then the <code>status</code> of cluster changes.</p>\n</blockquote>\n<p><div class=\"lightbox-wrapper\"><a class=\"lightbox\" href=\"https://global.discourse-cdn.com/foundationdb/original/2X/0/01af8b9f6aa2d3460012475f87184e3b86172100.png\" data-download-href=\"/uploads/short-url/eUA4hezgwH52TwO8dPu4VHNOWA.png?dl=1\" title=\"failure\" rel=\"noopener nofollow ugc\"><img src=\"https://global.discourse-cdn.com/foundationdb/optimized/2X/0/01af8b9f6aa2d3460012475f87184e3b86172100_2_690x227.png\" alt=\"failure\" data-base62-sha1=\"eUA4hezgwH52TwO8dPu4VHNOWA\" width=\"690\" height=\"227\" srcset=\"https://global.discourse-cdn.com/foundationdb/optimized/2X/0/01af8b9f6aa2d3460012475f87184e3b86172100_2_690x227.png, https://global.discourse-cdn.com/foundationdb/optimized/2X/0/01af8b9f6aa2d3460012475f87184e3b86172100_2_1035x340.png 1.5x, https://global.discourse-cdn.com/foundationdb/original/2X/0/01af8b9f6aa2d3460012475f87184e3b86172100.png 2x\" data-dominant-color=\"04080A\"><div class=\"meta\"><svg class=\"fa d-icon d-icon-far-image svg-icon\" aria-hidden=\"true\"><use href=\"#far-image\"></use></svg><span class=\"filename\">failure</span><span class=\"informations\">1325\u00d7437 33.4 KB</span><svg class=\"fa d-icon d-icon-discourse-expand svg-icon\" aria-hidden=\"true\"><use href=\"#discourse-expand\"></use></svg></div></a></div><br>\nIt seems the primary datacenter has changed to <code>DC3</code>,but fault tolerance changes to -1, and replication health keeps <code>initializing automatic data distribution</code> for a long time. However, read and write requests can be submitted by the cluster normally.<br>\n<code>fdbcli --exec 'status json'</code> shows <code>DC3</code> hasn\u2019t fully recovered yet<br>\n<img src=\"https://global.discourse-cdn.com/foundationdb/original/2X/2/2fc2c3cb47563a39d011a24a366032ba3c2d0024.png\" alt=\"failure2\" data-base62-sha1=\"6OvIOuXIo4kGP5QnchVUEvEbtic\" width=\"536\" height=\"153\"><br>\nAnd a stateless process deployed in <code>DC3</code> shows the recovery_state is still accepting_commits.<br>\n<img src=\"https://global.discourse-cdn.com/foundationdb/original/2X/f/f87ef30cd3c455569b08acd34207d91b25d90182.png\" alt=\"failure4\" data-base62-sha1=\"zsioPFiwf9iH20WDPRmY9h1Y7xo\" width=\"388\" height=\"87\"></p>\n<p>Question:</p>\n<ol>\n<li>Are there any problems with my cluster configuration? The status of <code>cluster hasn't fully recovered yet</code>   of remote datacenter is not the expect behavior  of me. Should the recovery_state of the cluster become <code>fully_recovered</code>? What can I do to  handle this problem?</li>\n<li>What should I do to recover the remote DC after the failure of primary datacenter? or the failure of satellite?</li>\n<li>I plan to simulate all data loss of <code>DC1</code>, The next step is to change  <code>regions.json</code> that sets priority of <code>DC1</code> to  -1,and <code>configure usable_regions=1</code> .Is it a safe step when facing these situations?<br>\nThanks in advance\uff01</li>\n</ol>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2022-05-17T08:55:43.396Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 41,
        "reads": 44,
        "readers_count": 43,
        "score": 193.8,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://global.discourse-cdn.com/foundationdb/original/2X/a/a4c7fc1d6114672c9792f82339ddf436e6d9a7bd.png",
            "internal": false,
            "reflection": false,
            "title": "a4c7fc1d6114672c9792f82339ddf436e6d9a7bd.png",
            "clicks": 0
          },
          {
            "url": "https://global.discourse-cdn.com/foundationdb/original/2X/0/01af8b9f6aa2d3460012475f87184e3b86172100.png",
            "internal": false,
            "reflection": false,
            "title": "01af8b9f6aa2d3460012475f87184e3b86172100.png",
            "clicks": 0
          },
          {
            "url": "https://forums.foundationdb.org/t/dataloss-when-doing-failover-with-a-multi-region-cluster/4921/2",
            "internal": true,
            "reflection": true,
            "title": "Dataloss when doing failover with a multi region cluster?",
            "clicks": 0
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1095,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 14549,
        "name": "Mark Sh1",
        "username": "MarkSh1",
        "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png",
        "created_at": "2024-11-20T13:39:15.333Z",
        "cooked": "<p>I have the same problem. I tried using versions 6.3, 7.1, 7.3 and the latest version 7.4 and got the same behavior. When I disconnect the main DC cluster, the cluster switches to the second region and hangs in the initialization status.</p>\n<pre><code class=\"lang-auto\">{\n  \"regions\":[\n    {\n        \"datacenters\":[\n          {\"id\":\"dc1\",\"priority\":2},\n          {\"id\":\"dc3\",\"priority\":1,\"satellite\":1}\n        ],\n        \"satellite_redundancy_mode\": \"one_satellite_double\",\n        \"satellite_logs\":2\n    },\n    {\n        \"datacenters\":[\n          {\"id\":\"dc2\",\"priority\":1},\n          {\"id\":\"dc4\",\"priority\":1,\"satellite\":1}\n        ],\n        \"satellite_redundancy_mode\": \"one_satellite_double\",\n        \"satellite_logs\":2\n    }\n  ]\n}\n</code></pre>\n<p>fdb&gt; status details</p>\n<pre><code class=\"lang-auto\">Configuration:\n  Redundancy mode        - single\n  Storage engine         - ssd-2\n  Coordinators           - 3\n  Usable Regions         - 2\n  Regions:\n    Remote -\n        Datacenter                    - dc1\n        Satellite datacenters         - dc3\n        Satellite Redundancy Mode     - one_satellite_double\n        Satellite Logs                - 2\n    Primary -\n        Datacenter                    - dc2\n        Satellite datacenters         - dc4\n        Satellite Redundancy Mode     - one_satellite_double\n        Satellite Logs                - 2\n\nCluster:\n  FoundationDB processes - 6\n  Zones                  - 6\n  Machines               - 6\n  Memory availability    - 8.0 GB per process on machine with least available\n  Fault Tolerance        - -1 machines\n\n  Warning: the database may have data loss and availability loss. Please restart following tlog interfaces, otherwise storage servers may never be able to catch up.\n  Old log epoch: 27 begin: 70577542348 end: 71344145316, missing log interfaces(id,address): 7b91b08e089a7e4e,\n\n  Server time            - 11/20/24 15:19:03\n\nData:\n  Replication health     - (Re)initializing automatic data distribution\n  Moving data            - unknown (initializing)\n  Sum of key-value sizes - unknown\n  Disk space used        - 420 MB\n\nOperating space:\n  Storage server         - 187.0 GB free on most full server\n  Log server             - 185.1 GB free on most full server\n\nWorkload:\n  Read rate              - 162 Hz\n  Write rate             - 9 Hz\n  Transactions started   - 60 Hz\n  Transactions committed - 9 Hz\n  Conflict rate          - 0 Hz\n\nBackup and DR:\n  Running backups        - 0\n  Running DRs            - 0\n\nProcess performance details:\n  10.121.35.122:4500      (  0% cpu;  0% machine; 0.000 Gbps;  0% disk IO; 0.1 GB / 8.0 GB RAM  )\n  10.121.35.200:4500      (  1% cpu;  1% machine; 0.000 Gbps;  6% disk IO; 0.2 GB / 8.0 GB RAM  )\n  10.121.35.210:4500      (  1% cpu;  1% machine; 0.000 Gbps;  6% disk IO; 0.2 GB / 8.0 GB RAM  )\n  10.121.35.230:4500      (  0% cpu;  0% machine; 0.000 Gbps;  0% disk IO; 0.2 GB / 8.0 GB RAM  )\n  10.121.35.240:4500      (  0% cpu;  0% machine; 0.000 Gbps;  0% disk IO; 0.2 GB / 8.0 GB RAM  )\n  10.121.35.245:4500      (  3% cpu;  3% machine; 0.001 Gbps;  6% disk IO; 0.3 GB / 8.0 GB RAM  )</code></pre>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2024-11-20T13:39:15.333Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 33,
        "readers_count": 32,
        "score": 26.6,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Mark Sh1",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1422,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 14554,
        "name": "Jingyu Zhou",
        "username": "jzhou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
        "created_at": "2024-11-22T17:06:58.223Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"Clindy\" data-post=\"1\" data-topic=\"3329\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img loading=\"lazy\" alt=\"\" width=\"24\" height=\"24\" src=\"https://avatars.discourse-cdn.com/v4/letter/c/f04885/48.png\" class=\"avatar\"> Clindy:</div>\n<blockquote>\n<p>accepting_commits</p>\n</blockquote>\n</aside>\n<p>This state means the database is available, i.e., read or write transactions can be performed.</p>\n<blockquote>\n<p>the database may have data loss and availability loss. Please restart following tlog interfaces, otherwise storage servers may never be able to catch up.<br>\nOld log epoch: 27 begin: 70577542348 end: 71344145316, missing log interfaces(id,address): 7b91b08e089a7e4e,</p>\n</blockquote>\n<p>This is saying because of the DC failure, the new primary region can\u2019t fetch the tail of mutation logs from the failed tlogs. Until the failed tlog is brought up, some storage servers can\u2019t catch up (because they have to apply mutation logs in order and miss some of the logs).</p>\n<p>The fault tolerance of your configuration is 1 DC + 1 satellite tlog. Did you tear down the whole primary region?</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2024-11-22T17:06:58.223Z",
        "reply_count": 3,
        "reply_to_post_number": 2,
        "quote_count": 1,
        "incoming_link_count": 8,
        "reads": 31,
        "readers_count": 30,
        "score": 61.2,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Jingyu Zhou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1422,
          "username": "MarkSh1",
          "name": "Mark Sh1",
          "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": true,
        "admin": true,
        "staff": true,
        "user_id": 454,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 14557,
        "name": "Mark Sh1",
        "username": "MarkSh1",
        "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png",
        "created_at": "2024-11-26T10:55:40.101Z",
        "cooked": "<p>In first region I turned off only the primary dc1, the satellite dc3 continued to work. The main dc2 in the second region should pick up the log from the satellite dc3 of the first region, but the cluster state remains in initialization all time</p>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2024-11-26T12:31:14.518Z",
        "reply_count": 0,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 27,
        "readers_count": 26,
        "score": 25.4,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Mark Sh1",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 4,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 454,
          "username": "jzhou",
          "name": "Jingyu Zhou",
          "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1422,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 14685,
        "name": "Mark Sh1",
        "username": "MarkSh1",
        "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png",
        "created_at": "2025-01-21T11:19:31.754Z",
        "cooked": "<p>Why the new primary region can\u2019t use logs from the satellite? Why does it need logs from a faulty data center?<br>\nIf I turn off DC1, I see in the log:</p>\n<pre><code class=\"lang-auto\">\"log_interfaces\": [\n      {\n        \"healthy\": false,\n        \"id\": \"edb6db3124477c84\"\n      },\n...\n\"possibly_losing_data\": true,\n</code></pre>\n<p>And the cluster enters the mode</p>\n<pre><code class=\"lang-auto\">{\n  \"can_clean_bounce\": false,\n  \"reason\": \"cluster hasn't fully recovered yet\"\n}\n{\n  \"description\": \"(Re)initializing automatic data distribution\",\n  \"name\": \"initializing\"\n}\n</code></pre>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-01-21T11:19:31.754Z",
        "reply_count": 1,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 20,
        "reads": 27,
        "readers_count": 26,
        "score": 110.4,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Mark Sh1",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 454,
          "username": "jzhou",
          "name": "Jingyu Zhou",
          "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1422,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 14838,
        "name": "Mark Sh1",
        "username": "MarkSh1",
        "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png",
        "created_at": "2025-04-17T10:34:56.116Z",
        "cooked": "<p>Fix status [link] (<a href=\"https://github.com/apple/foundationdb/pull/12071\" class=\"inline-onebox\" rel=\"noopener nofollow ugc\">Fixed database status in multi-region mode when primary DC fails by MarkSh1 \u00b7 Pull Request #12071 \u00b7 apple/foundationdb \u00b7 GitHub</a>)</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-04-17T10:34:56.116Z",
        "reply_count": 2,
        "reply_to_post_number": 5,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 25,
        "readers_count": 24,
        "score": 20.0,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Mark Sh1",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/pull/12071",
            "internal": false,
            "reflection": false,
            "title": "Fixed database status in multi-region mode when primary DC fails by MarkSh1 \u00b7 Pull Request #12071 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 15
          }
        ],
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1422,
          "username": "MarkSh1",
          "name": "Mark Sh1",
          "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1422,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 14986,
        "name": "Matthieu Patou",
        "username": "mpatou_openai",
        "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png",
        "created_at": "2025-06-12T01:50:02.866Z",
        "cooked": "<p>More than the status display issue my main issue is with the data movement it seems that while this is happening the data mover will not be working and hence if we starts to see issue on the secondary region (ie. a pod/node is failing) then we will not try to rebalance to others ss which seems more risky.</p>",
        "post_number": 7,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-06-12T01:50:02.866Z",
        "reply_count": 0,
        "reply_to_post_number": 6,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 18,
        "readers_count": 17,
        "score": 8.6,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Matthieu Patou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1422,
          "username": "MarkSh1",
          "name": "Mark Sh1",
          "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1484,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/7",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 14988,
        "name": "Grigory Demchenko",
        "username": "gridem-openai",
        "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png",
        "created_at": "2025-06-12T02:07:39.243Z",
        "cooked": "<p>I see that there was a fix <a href=\"https://github.com/apple/foundationdb/pull/12071\" class=\"inline-onebox\" rel=\"noopener nofollow ugc\">Fixed database status in multi-region mode when primary DC fails by MarkSh1 \u00b7 Pull Request #12071 \u00b7 apple/foundationdb \u00b7 GitHub</a>, that fixed a database status. But the actual code still contains the warning about potential data loss. What is the point of the PR? It seems that original problem was not solved.</p>",
        "post_number": 8,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-06-12T02:07:39.243Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 19,
        "readers_count": 18,
        "score": 8.8,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Grigory Demchenko",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/pull/12071",
            "internal": false,
            "reflection": false,
            "title": "Fixed database status in multi-region mode when primary DC fails by MarkSh1 \u00b7 Pull Request #12071 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 4
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1563,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/8",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15180,
        "name": "Jillian Crossley",
        "username": "noctella",
        "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
        "created_at": "2025-08-15T13:44:48.601Z",
        "cooked": "<p>I am also seeing the exact same problem in 7.4 \u2013 kill the primary DC (which has a satellite), it fails over to secondary region, then gets stuck:</p>\n<pre><code class=\"lang-auto\"> Warning: the database may have data loss and availability loss. Please restart following tlog interfaces, otherwise storage servers may never be able to catch up.\n  Old log epoch: 12 begin: 827334449 end: 1093552744, missing log interfaces(id,address): 61f46c21d2e4658d, 6c502d17604de6a5, 7e3b34298e52abf4,\n\n  Server time            - 08/15/25 13:25:03\n\nData:\n  Replication health     - (Re)initializing automatic data distribution\n  Moving data            - unknown (initializing)\n</code></pre>",
        "post_number": 9,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-08-15T13:44:48.601Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 19,
        "readers_count": 18,
        "score": 3.8,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Jillian Crossley",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1594,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/9",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15205,
        "name": "Mark Sh1",
        "username": "MarkSh1",
        "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png",
        "created_at": "2025-08-19T13:17:57.809Z",
        "cooked": "<p>I\u2019ve done some tests, the results are in the table.</p>\n<p>It turns out that data loss is only possible in the A3 test.<br>\nTotal: if remote_log_fault_tolerance: -1, then we write about possible data loss</p>\n<p>I fixed it in PR.</p>\n<p><div class=\"lightbox-wrapper\"><a class=\"lightbox\" href=\"https://global.discourse-cdn.com/foundationdb/original/2X/e/e858a027b4cb9cd24e717bdaf0fb6d7b1c3352f2.png\" data-download-href=\"/uploads/short-url/x9qEsHLYwcb1nAJirAIhcvhVBaa.png?dl=1\" title=\"image\" rel=\"noopener nofollow ugc\"><img src=\"https://global.discourse-cdn.com/foundationdb/original/2X/e/e858a027b4cb9cd24e717bdaf0fb6d7b1c3352f2.png\" alt=\"image\" data-base62-sha1=\"x9qEsHLYwcb1nAJirAIhcvhVBaa\" width=\"690\" height=\"362\" data-dominant-color=\"EBDAD5\"><div class=\"meta\"><svg class=\"fa d-icon d-icon-far-image svg-icon\" aria-hidden=\"true\"><use href=\"#far-image\"></use></svg><span class=\"filename\">image</span><span class=\"informations\">1125\u00d7591 18 KB</span><svg class=\"fa d-icon d-icon-discourse-expand svg-icon\" aria-hidden=\"true\"><use href=\"#discourse-expand\"></use></svg></div></a></div></p>",
        "post_number": 10,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-08-19T13:23:55.176Z",
        "reply_count": 1,
        "reply_to_post_number": 8,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 19,
        "readers_count": 18,
        "score": 18.8,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Mark Sh1",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1563,
          "username": "gridem-openai",
          "name": "Grigory Demchenko",
          "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1422,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/10",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15291,
        "name": "Grigory Demchenko",
        "username": "gridem-openai",
        "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png",
        "created_at": "2025-09-03T01:46:37.456Z",
        "cooked": "<p>MarkSh1, thank you for providing an update. What is not clear is that what your PR is doing. From my understanding, it doesn\u2019t fix the situation, the warning still be there, no any logic change. So, what is the point of the PR?</p>\n<p>According to your table with tests. I see 2 regions configuration, but it\u2019s not clear about DCs and association of tlogs with different DCs. The original post operates with at least 3 DCs: 1 for primary, 1 for satellite, 1 for secondary. There is another option of using 4th DC, for secondary satellite, but let\u2019s omit it for now.</p>\n<p>So in your tests you still see some warning, but the main question: is there any real data loss that may happen? If yes, under what conditions? If no - then why do we have this warning at all?</p>\n<p>If there is a possible of dataloss, then what\u2019s the point of having primary and satellites at all? The main motivation for such a deployment is to use satellite with synchronous replication, that allows to catch up from secondary during DC failover. If it\u2019s not the case, then what\u2019s the point of having it?</p>",
        "post_number": 11,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-09-03T01:58:28.162Z",
        "reply_count": 0,
        "reply_to_post_number": 10,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 9,
        "readers_count": 8,
        "score": 6.8,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Grigory Demchenko",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1422,
          "username": "MarkSh1",
          "name": "Mark Sh1",
          "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1563,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/11",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15293,
        "name": "Matthieu Patou",
        "username": "mpatou_openai",
        "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png",
        "created_at": "2025-09-03T06:11:19.046Z",
        "cooked": "<p>Hi <a class=\"mention\" href=\"/u/jzhou\">@jzhou</a></p>\n<p>&gt;&gt;the database may have data loss and availability loss. Please restart following tlog interfaces, otherwise storage servers may never be able to catch up. Old log epoch: 27 begin: 70577542348 end: 71344145316, missing log interfaces(id,address): 7b91b08e089a7e4e,</p>\n<p>&gt;This is saying because of the DC failure, the new primary region can\u2019t fetch the tail of mutation logs from the failed tlogs. Until the failed tlog is brought up, some storage servers can\u2019t catch up (because they have to apply mutation logs in order and miss some of the logs).</p>\n<p>We were seeing similar messages with a cluster that has a primary with a replication factor of 2 and 4 Tlogs and a satellite with 2 tlogs and a <code>one_satellite_double</code> mode.<br>\nWhat happened is that we were shutting down the main DC and so FDB doesn\u2019t have a quorum for the tlogs but still we have some copies in the satellite.</p>\n<p>What if we can\u2019t recover the original DC at all ? Isn\u2019t there a risk that can never catch up because we can\u2019t apply the mutation log and if so doesn\u2019t defeat the purpose of the satellite ?</p>",
        "post_number": 12,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-09-03T06:11:19.046Z",
        "reply_count": 1,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 9,
        "readers_count": 8,
        "score": 6.8,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Matthieu Patou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 454,
          "username": "jzhou",
          "name": "Jingyu Zhou",
          "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1484,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/12",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15294,
        "name": "Jingyu Zhou",
        "username": "jzhou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
        "created_at": "2025-09-03T15:35:07.461Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"mpatou_openai\" data-post=\"12\" data-topic=\"3329\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/mpatou_openai/48/1883_2.png\" class=\"avatar\"> mpatou_openai:</div>\n<blockquote>\n<p>What happened is that we were shutting down the main DC and so FDB doesn\u2019t have a quorum for the tlogs but still we have some copies in the satellite.</p>\n<p>What if we can\u2019t recover the original DC at all ? Isn\u2019t there a risk that can never catch up because we can\u2019t apply the mutation log and if so doesn\u2019t defeat the purpose of the satellite ?</p>\n</blockquote>\n</aside>\n<p>If main DC is down, the database will automatically fail over to the remote region. And the remote region can pull mutation logs from original satellite, thus no data loss. What I meant in \u201cUntil the failed tlog is brought up, some storage servers can\u2019t catch up\u201d is referring to the original primary side storage servers. After failover, the new primary side won\u2019t have data loss.</p>",
        "post_number": 13,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-09-03T15:35:07.461Z",
        "reply_count": 1,
        "reply_to_post_number": 12,
        "quote_count": 1,
        "incoming_link_count": 0,
        "reads": 10,
        "readers_count": 9,
        "score": 7.0,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Jingyu Zhou",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": true,
        "admin": true,
        "staff": true,
        "user_id": 454,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/13",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15296,
        "name": "Grigory Demchenko",
        "username": "gridem-openai",
        "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png",
        "created_at": "2025-09-03T16:08:23.538Z",
        "cooked": "<blockquote>\n<p>After failover, the new primary side won\u2019t have data loss</p>\n</blockquote>\n<p>So do you mean that after switching from primary to secondary there won\u2019t be any data loss? In such a case, what is the point of having the warning and disabling the data distribution? Is it a bug?</p>",
        "post_number": 14,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-09-03T16:08:23.538Z",
        "reply_count": 1,
        "reply_to_post_number": 13,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 10,
        "readers_count": 9,
        "score": 27.0,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Grigory Demchenko",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 454,
          "username": "jzhou",
          "name": "Jingyu Zhou",
          "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1563,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/14",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 15299,
        "name": "Grigory Demchenko",
        "username": "gridem-openai",
        "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png",
        "created_at": "2025-09-03T17:56:46.220Z",
        "cooked": "<aside class=\"quote no-group\" data-username=\"MarkSh1\" data-post=\"6\" data-topic=\"3329\">\n<div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img alt=\"\" width=\"24\" height=\"24\" src=\"https://sea1.discourse-cdn.com/foundationdb/user_avatar/forums.foundationdb.org/marksh1/48/1789_2.png\" class=\"avatar\"> MarkSh1:</div>\n<blockquote>\n<p>Fixed database status in multi-region mode when primary DC fails by MarkSh1 \u00b7 Pull Request <span class=\"hashtag-raw\">#12071</span> \u00b7 apple/foundationdb \u00b7 GitHub</p>\n</blockquote>\n</aside>\n<p>For this diff it looks like it fixes warning only: now it may not be shown in fdbcli status. But the real problem is that FDB reports that <code>dataLoss == -1</code> and <code>availLoss == -1</code>. Which has implications on data mover (at least, maybe there are some other consequences). So the complaining here is not just having a warning which is misleading according to discussion, but that it has a consequences on the entire FDB system: the system enters into \u201cdegraded\u201d mode where at least data movement is disabled. Maybe there are some other consequences which is hidden and not shown in fdbcli.</p>\n<p>So the biggest issue is that \u201cdegraded\u201d mode is not expected for failover from primary to secondary. The expectation is that secondary should continue under normal situation/condition.</p>",
        "post_number": 15,
        "post_type": 1,
        "posts_count": 15,
        "updated_at": "2025-09-03T17:56:46.220Z",
        "reply_count": 0,
        "reply_to_post_number": 14,
        "quote_count": 1,
        "incoming_link_count": 4,
        "reads": 10,
        "readers_count": 9,
        "score": 12.0,
        "yours": false,
        "topic_id": 3329,
        "topic_slug": "3dc2regions-simulating-primary-datacenter-failure",
        "display_username": "Grigory Demchenko",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 1563,
          "username": "gridem-openai",
          "name": "Grigory Demchenko",
          "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 1563,
        "hidden": false,
        "trust_level": 1,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/3dc2regions-simulating-primary-datacenter-failure/3329/15",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      11129,
      14549,
      14554,
      14557,
      14685,
      14838,
      14986,
      14988,
      15180,
      15205,
      15291,
      15293,
      15294,
      15296,
      15299
    ]
  },
  "timeline_lookup": [
    [
      1,
      1254
    ],
    [
      2,
      335
    ],
    [
      3,
      333
    ],
    [
      4,
      329
    ],
    [
      5,
      273
    ],
    [
      6,
      187
    ],
    [
      7,
      132
    ],
    [
      9,
      67
    ],
    [
      10,
      63
    ],
    [
      11,
      49
    ],
    [
      13,
      48
    ]
  ],
  "suggested_topics": [],
  "tags": [
    "bindings"
  ],
  "tags_descriptions": {},
  "fancy_title": "3DC2regions&ndash;Simulating Primary Datacenter Failure",
  "id": 3329,
  "title": "3DC2regions--Simulating Primary Datacenter Failure",
  "posts_count": 15,
  "created_at": "2022-05-17T08:55:43.320Z",
  "views": 611,
  "reply_count": 11,
  "like_count": 0,
  "last_posted_at": "2025-09-03T17:56:46.220Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "3dc2regions-simulating-primary-datacenter-failure",
  "category_id": 7,
  "word_count": 1910,
  "deleted_at": null,
  "user_id": 1095,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": "https://global.discourse-cdn.com/foundationdb/original/2X/a/a4c7fc1d6114672c9792f82339ddf436e6d9a7bd.png",
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_3329",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 15,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 6,
  "show_read_indicator": false,
  "thumbnails": [
    {
      "max_width": null,
      "max_height": null,
      "width": 637,
      "height": 781,
      "url": "https://global.discourse-cdn.com/foundationdb/original/2X/a/a4c7fc1d6114672c9792f82339ddf436e6d9a7bd.png"
    }
  ],
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "Simulating FDB data center failure",
      "id": 1790,
      "title": "Simulating FDB data center failure",
      "slug": "simulating-fdb-data-center-failure",
      "posts_count": 5,
      "reply_count": 2,
      "highest_post_number": 5,
      "image_url": null,
      "created_at": "2019-11-27T00:51:36.820Z",
      "last_posted_at": "2019-12-09T22:25:12.268Z",
      "bumped": true,
      "bumped_at": "2019-12-09T22:25:12.268Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [
        "performance"
      ],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 977,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 550,
            "username": "ntrhieu89",
            "name": "Hieu Nguyen",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ntrhieu89/{size}/587_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Two region setup: fdb doesn&rsquo;t switch back to recovered primary idc",
      "id": 3102,
      "title": "Two region setup: fdb doesn't switch back to recovered primary idc",
      "slug": "two-region-setup-fdb-doesnt-switch-back-to-recovered-primary-idc",
      "posts_count": 5,
      "reply_count": 2,
      "highest_post_number": 5,
      "image_url": null,
      "created_at": "2022-01-06T09:20:23.617Z",
      "last_posted_at": "2022-01-25T09:00:26.631Z",
      "bumped": true,
      "bumped_at": "2022-01-25T09:00:26.631Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 507,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 1037,
            "username": "leonliao",
            "name": "Leonliao",
            "avatar_template": "/user_avatar/forums.foundationdb.org/leonliao/{size}/1244_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "6.0.18 Reporting incorrect Fault Tolerance via fdbcli with triple redundancy mode?",
      "id": 1282,
      "title": "6.0.18 Reporting incorrect Fault Tolerance via fdbcli with triple redundancy mode?",
      "slug": "6-0-18-reporting-incorrect-fault-tolerance-via-fdbcli-with-triple-redundancy-mode",
      "posts_count": 15,
      "reply_count": 8,
      "highest_post_number": 16,
      "image_url": null,
      "created_at": "2019-04-04T19:04:42.341Z",
      "last_posted_at": "2019-04-06T00:41:42.940Z",
      "bumped": true,
      "bumped_at": "2019-04-06T00:41:42.940Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 2,
      "views": 1976,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 490,
            "username": "rjenkins",
            "name": "Ray Jenkins",
            "avatar_template": "/user_avatar/forums.foundationdb.org/rjenkins/{size}/487_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 81,
            "username": "ryanworl",
            "name": "Ryan Worl",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ryanworl/{size}/440_2.png",
            "trust_level": 3
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 54,
            "username": "Evan",
            "name": "Evan Tschannen",
            "avatar_template": "/user_avatar/forums.foundationdb.org/evan/{size}/104_2.png",
            "moderator": true,
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Dataloss when doing failover with a multi region cluster?",
      "id": 4921,
      "title": "Dataloss when doing failover with a multi region cluster?",
      "slug": "dataloss-when-doing-failover-with-a-multi-region-cluster",
      "posts_count": 10,
      "reply_count": 6,
      "highest_post_number": 10,
      "image_url": null,
      "created_at": "2025-05-31T01:52:41.383Z",
      "last_posted_at": "2025-09-05T12:15:12.586Z",
      "bumped": true,
      "bumped_at": "2025-09-05T12:15:12.586Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 2,
      "views": 181,
      "category_id": 17,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 1484,
            "username": "mpatou_openai",
            "name": "Matthieu Patou",
            "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 454,
            "username": "jzhou",
            "name": "Jingyu Zhou",
            "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
            "admin": true,
            "moderator": true,
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 849,
            "username": "johscheuer",
            "name": "Johannes Scheuermann",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/j/f475e1/{size}.png",
            "trust_level": 2
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 1594,
            "username": "noctella",
            "name": "Jillian Crossley",
            "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
            "trust_level": 1
          }
        }
      ]
    },
    {
      "fancy_title": "Fault Tolerance changes from &ldquo;2 machines&rdquo; to &ldquo;0 machines (2 without data loss)&rdquo;",
      "id": 1408,
      "title": "Fault Tolerance changes from \"2 machines\" to \"0 machines (2 without data loss)\"",
      "slug": "fault-tolerance-changes-from-2-machines-to-0-machines-2-without-data-loss",
      "posts_count": 2,
      "reply_count": 0,
      "highest_post_number": 2,
      "image_url": null,
      "created_at": "2019-05-30T00:40:05.914Z",
      "last_posted_at": "2019-06-05T23:05:50.387Z",
      "bumped": true,
      "bumped_at": "2019-06-05T23:05:50.387Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 574,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 577,
            "username": "binzhangebay",
            "name": "binzhang",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/b/6a8cbe/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 1422,
        "username": "MarkSh1",
        "name": "Mark Sh1",
        "avatar_template": "/user_avatar/forums.foundationdb.org/marksh1/{size}/1789_2.png",
        "post_count": 5,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 1563,
        "username": "gridem-openai",
        "name": "Grigory Demchenko",
        "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png",
        "post_count": 4,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 454,
        "username": "jzhou",
        "name": "Jingyu Zhou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/jzhou/{size}/445_2.png",
        "post_count": 2,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "admin": true,
        "moderator": true,
        "trust_level": 2
      },
      {
        "id": 1484,
        "username": "mpatou_openai",
        "name": "Matthieu Patou",
        "avatar_template": "/user_avatar/forums.foundationdb.org/mpatou_openai/{size}/1883_2.png",
        "post_count": 2,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 2
      },
      {
        "id": 1095,
        "username": "Clindy",
        "name": "",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/f04885/{size}.png",
        "post_count": 1,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      },
      {
        "id": 1594,
        "username": "noctella",
        "name": "Jillian Crossley",
        "avatar_template": "/user_avatar/forums.foundationdb.org/noctella/{size}/2015_2.png",
        "post_count": 1,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 1
      }
    ],
    "created_by": {
      "id": 1095,
      "username": "Clindy",
      "name": "",
      "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/f04885/{size}.png"
    },
    "last_poster": {
      "id": 1563,
      "username": "gridem-openai",
      "name": "Grigory Demchenko",
      "avatar_template": "/user_avatar/forums.foundationdb.org/gridem-openai/{size}/1981_2.png"
    },
    "links": [
      {
        "url": "https://github.com/apple/foundationdb/pull/12071",
        "title": "Fixed database status in multi-region mode when primary DC fails by MarkSh1 \u00b7 Pull Request #12071 \u00b7 apple/foundationdb \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 19,
        "user_id": 1422,
        "domain": "github.com",
        "root_domain": "github.com"
      }
    ]
  },
  "bookmarks": []
}